"""The published report cites its sources: the generated "Sources per check" appendix.

`cc_tasks/2026-09-11_report_sources_appendix.md` §3. "Citable by a stranger" means a stranger
holding the PDF. The appendix is generated by `report_traceability.sources_appendix` from the
graph, the framework of record and the corpus manifest; these tests hold its gate:

* the fragment exists, is included by the appendix section, and reaches the built markdown;
* every check the report carries has at least one row, and every row's doc_id is in the
  manifest;
* A3 and A10 carry their locators;
* the locator parser and the citation renderer behave on the shapes the evidence cells use;
* the prose-named product legs are read from the sections, not typed.

The graph-dependent cases skip when Neo4j is down, as the projection round-trip does; the
fragment-file cases do not.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))

import report_traceability as RT                                    # noqa: E402

FRAGMENT = REPO / "docs" / "reports" / "generated" / "sources_per_check.md"
SECTION = REPO / "docs" / "reports" / "sections" / "80_appendix.md"
BUILT = REPO / "docs" / "reports" / "2026-09_fss_ai_readiness_L0.md"
MANIFEST = json.loads((REPO / "corpus" / "manifest.json").read_text(encoding="utf-8"))["entries"]

ROW = re.compile(r"^\| (?P<check>[^|]+?) \| (?P<indicator>[^|]*?) \| (?P<source>.*?) \| "
                 r"(?P<doc>[^|]*?) \| (?P<locator>.*?) \|$")


def rows(text: str) -> list:
    out = []
    for line in text.splitlines():
        m = ROW.match(line)
        if m and m.group("check") not in ("Check", "---"):
            d = m.groupdict()
            d["doc"] = d["doc"].strip("` ")
            out.append(d)
    return out


# ------------------------------------------------------------------ the fragment on disk
def test_the_fragment_exists_and_the_appendix_section_includes_it():
    assert FRAGMENT.is_file(), "run scripts/build_l0_report.py; the builder writes it"
    assert "<!-- include: sources_per_check -->" in SECTION.read_text(encoding="utf-8")
    # inside the numerals-exempt region, like the other generated method tables
    sec = SECTION.read_text(encoding="utf-8")
    assert sec.index("<!-- lint: numerals-exempt -->") < sec.index("include: sources_per_check") \
        < sec.index("<!-- lint: numerals-enforced -->")


def test_every_check_the_report_carries_has_a_row():
    got = {r["check"] for r in rows(FRAGMENT.read_text(encoding="utf-8"))}
    want = set(RT.appendix_legs())
    assert want <= got, sorted(want - got)


def test_every_row_doc_id_is_in_the_manifest():
    bad = [r for r in rows(FRAGMENT.read_text(encoding="utf-8")) if r["doc"] and r["doc"] not in MANIFEST]
    assert not bad, [(r["check"], r["doc"]) for r in bad]


def test_a3_and_a10_rows_carry_their_locators():
    by = {}
    for r in rows(FRAGMENT.read_text(encoding="utf-8")):
        by.setdefault(r["check"], {})[r["doc"]] = r["locator"]
    assert "BP 17" in by["A3"]["w3c-dwbp-2017"]
    assert "downloadURL" in by["A3"]["dcat-us-1-1-schema"]
    assert "A1 and A1.1" in by["A3"]["wilkinson-2016-fair-guiding-principles"]
    assert "BP 9" in by["A10"]["w3c-dwbp-2017"] and "BP 27" in by["A10"]["w3c-dwbp-2017"]
    assert "F1" in by["A10"]["wilkinson-2016-fair-guiding-principles"]


def test_a1_a8_b3_d4_rows_carry_their_locators():
    """`cc_tasks/2026-09-12_a1_a8_b3_d4_sources.md` §1. Each locator is a string read out of the
    cited document in that task, not off its title — the BP 10 discipline
    (`cc_tasks/2026-09-11_a3_a10_sources_RESULT.md` §4). A row whose Source column is filled and
    whose Locator column is empty is a citation with no page number, which is what these pin."""
    by = {}
    for r in rows(FRAGMENT.read_text(encoding="utf-8")):
        by.setdefault(r["check"], {})[r["doc"]] = r["locator"]
    assert "BP 12" in by["A1"]["w3c-dwbp-2017"]
    assert "3502" in by["A1"]["foundations-for-evidence-based-policymaking-act-of-2018-evid"]
    assert "Machine-Readable" in by["A1"][
        "m-25-05-phase-2-implementation-of-the-evidence-act-open-gove"]
    assert "BP 7" in by["A8"]["w3c-dwbp-2017"] and "BP 21" in by["A8"]["w3c-dwbp-2017"]
    assert "modified" in by["A8"]["dcat-us-1-1-schema"]
    assert "timeliness" in by["A8"]["omb-m-23-22-digital-first-public-experience"]
    assert "client-side rendering" in by["B3"]["bing-webmaster-guidelines"]
    assert "HTML" in by["B3"]["omb-m-23-22-digital-first-public-experience"]
    assert "3511" in by["D4"]["foundations-for-evidence-based-policymaking-act-of-2018-evid"]
    assert "data.json" in by["D4"][
        "m-25-05-phase-2-implementation-of-the-evidence-act-open-gove"]
    assert "Public Data Listing" in by["D4"]["dcat-us-1-1-schema"]


def test_every_pinned_leg_reaches_a_source_in_the_fragment():
    """The a3a10 invariant, read off the PDF's own table rather than the graph. Twelve legs
    since `cc_tasks/2026-09-12_a1_a8_b3_d4_sources.md` widened `RT.LEGS`; a leg that is allowed
    to reach no source is named in `tests/test_report_traceability.ALLOW_ZERO_SOURCES`, and
    while that mapping is empty this holds for every check the report carries."""
    got = rows(FRAGMENT.read_text(encoding="utf-8"))
    for leg in RT.LEGS:
        assert any(r["check"] == leg and r["doc"] for r in got), leg


def test_the_built_markdown_carries_the_fragment_verbatim():
    if not BUILT.is_file():
        pytest.skip("the report has not been built")
    frag = FRAGMENT.read_text(encoding="utf-8").rstrip("\n")
    assert frag in BUILT.read_text(encoding="utf-8")


def test_nothing_in_the_fragment_is_typed():
    """Every doc_id the fragment names is one the graph reaches for that leg; the check codes
    are the appendix legs and nothing else."""
    got = rows(FRAGMENT.read_text(encoding="utf-8"))
    assert {r["check"] for r in got} == set(RT.appendix_legs())
    framework = json.loads(RT.FRAMEWORK.read_text(encoding="utf-8"))
    evidenced = {}
    for e in framework["edges"]:
        if e["type"] == "EVIDENCED_BY":
            evidenced.setdefault(e["from"], set()).add(e["properties"]["doc_id"])
    for r in got:
        if r["doc"]:
            code = RT.FRAMEWORK_CODE.get(r["check"], r["check"])
            assert r["doc"] in evidenced.get(f"ind:{code}", set()), (r["check"], r["doc"])


# ------------------------------------------------------------------ the pieces
def test_product_legs_named_by_prose_are_read_from_the_sections(tmp_path):
    (tmp_path / "a.md").write_text(
        "x {{result:scan_l0_product_a3_pass_2026:value}} y "
        "{{result:scan_l0_product_b3_applicable_n_2026:value}} "
        "{{result:scan_l0_product_a3_error_2026:value}}", encoding="utf-8")
    (tmp_path / "b.md").write_text("{{result:scan_l0_product_d4_pass_x:value}}", encoding="utf-8")
    assert RT.product_legs_named_by_prose(tmp_path) == ["B3", "D4"]   # A3 is named in code
    # `LEGS` IS the read, since 2026-09-12: the seven named in code followed by whatever the
    # sections name. The two must not drift, or the appendix prints a row no test pins.
    assert RT.appendix_legs() == RT.LEGS
    assert RT.LEGS[:7] == RT._NAMED_IN_CODE


def test_locators_are_the_parenthetical_after_the_slug_balanced():
    cell = ('`w3c-dwbp-2017` (BP 17, provide bulk download: "enable (all) consumers"); '
            '`bare-slug-here`; `dcat-us-1-1-schema` (distribution → downloadURL)')
    assert RT.locators(cell) == {
        "w3c-dwbp-2017": 'BP 17, provide bulk download: "enable (all) consumers"',
        "bare-slug-here": "",
        "dcat-us-1-1-schema": "distribution → downloadURL"}


def test_citation_renders_what_the_manifest_has_and_reports_what_it_lacks():
    full = {"identity": {"authors_or_org": ["A. Author", "et al."], "title": "T | pipe",
                         "pub_year": "2017-01-31", "source_url": "https://x.example/"}}
    text, missing = RT.citation(full)
    assert text == "A. Author; et al. *T \\| pipe*. 2017. <https://x.example/>."
    assert missing == []
    nd = {"identity": {"authors_or_org": ["Org"], "title": "T", "pub_year": "n.d.",
                       "source_url": "https://x.example/"}}
    text, missing = RT.citation(nd)
    assert text == "Org. *T*. <https://x.example/>."
    assert missing == ["pub_year"]
    text, missing = RT.citation({"identity": {"title": "Only"}})
    assert text == "*Only*." and missing == ["authors_or_org", "pub_year", "source_url"]


# ------------------------------------------------------------------ against the graph
@pytest.fixture(scope="module")
def session():
    try:
        sys.path.insert(0, "/Users/brock/GitHub/seldon")
        from seldon.config import get_neo4j_driver, load_project_config
        cfg = load_project_config(REPO)
        drv = get_neo4j_driver(cfg)
        with drv.session(database=cfg["neo4j"]["database"]) as s:
            s.run("RETURN 1").single()
    except Exception as exc:                                        # noqa: BLE001
        pytest.skip(f"Neo4j unreachable: {exc}")
    with drv.session(database=cfg["neo4j"]["database"]) as s:
        yield s
    drv.close()


def test_the_fragment_on_disk_is_what_the_graph_generates_now(session):
    """A stale fragment is a citation list from another revision of the graph."""
    text, report = RT.sources_appendix(session)
    assert text == FRAGMENT.read_text(encoding="utf-8")
    assert report["doc_ids_not_in_manifest"] == []


def test_a_doc_id_outside_the_manifest_is_refused_and_nothing_is_written(session, tmp_path):
    framework = json.loads(RT.FRAMEWORK.read_text(encoding="utf-8"))
    manifest = json.loads(RT.MANIFEST.read_text(encoding="utf-8"))["entries"]
    manifest = {k: v for k, v in manifest.items() if k != "w3c-dwbp-2017"}
    _text, report = RT.sources_appendix(session, framework, manifest)
    assert ("A3", "w3c-dwbp-2017") in report["doc_ids_not_in_manifest"]
    out = tmp_path / "sources_per_check.md"
    with pytest.raises(SystemExit, match="does not hold"):
        with pytest.MonkeyPatch.context() as mp:
            mp.setattr(RT, "MANIFEST", _write_manifest(tmp_path, manifest))
            RT.write_sources_appendix(session, out)
    assert not out.exists()


def _write_manifest(tmp_path: Path, entries: dict) -> Path:
    p = tmp_path / "manifest.json"
    p.write_text(json.dumps({"entries": entries}), encoding="utf-8")
    return p
