"""G4's two sources carry a locator a stranger can turn to, and `docs/progress/` is compared
to the record it is a view of.

`cc_tasks/2026-09-19_g4_locators_and_progress_drift.md`, decisions 1 to 4.

Two guards, one file, because they are the same rule applied twice: **a generated consumer is
compared to its source, and a citation is checked against the document rather than believed.**

* **The locator half** (decisions 1 to 3). G4's Evidence cell is the authored source of the
  sources-appendix Locator column. A cell that names a document and no place in it is a
  citation with no page number — DN-001's floor is that a stranger can follow it. So every
  double-quoted span in the cell must be verbatim from the document it is attached to, checked
  through `kg/extraction/grounding.py`, the same validator invariant 3 holds every extracted
  node to. Nothing here is typed: the quotes are READ from the framework of record, and the
  record is asserted equal to the skeleton cell that authors it.

  A clause the document does not support gets the words `general support; no pinpoint`, never
  an invented locator, so the three legal outcomes of decision 2 are all expressible and only
  the silent fourth — a Source column filled and a Locator column empty — fails.

  **Two renderings, one document.** These two sources are PDFs. `state/docling_md/` holds the
  layout-aware Docling conversion (the reading substrate, `scripts/t1_build_index.py --phase
  convert`); `run_bulk_extraction.doc_text` reads PDFs through `pypdf`, because
  `kg.ingest.gate.substrate_path` returns None for them by design. Both are lossy views of the
  same sha256-verified bytes and they do NOT agree character for character: the Working Paper's
  Introduction carries U+2019 in `agency's`, which Docling normalises to an ASCII apostrophe
  and NFKC does not map. A span is grounded when it grounds in a rendering that is on disk,
  and the assertion message names the result per rendering, so a quote nobody can find in any
  rendering fails and a converter idiosyncrasy does not force the citation to be truncated
  mid-sentence to avoid a character.

  Both renderings are gitignored, rebuildable projections. A document with neither on disk
  skips, naming the command that rebuilds one — the convention the Neo4j-backed tests use.

* **The drift half** (decision 4). `docs/progress/` is generated by `scripts/framework_progress
  .py --cycle <cycle>` from `framework/ai_readiness_framework.json`. `tests/test_scan_run_2.py`
  ties the page to the cycle of record's denominator and nothing tied it to the framework
  record: the 2026-09-19 re-snapshot's regeneration moved counts that had been wrong on the
  page since 2026-09-11 and no test had noticed (`cc_tasks/2026-09-19_resnapshot_rj4_RESULT.md`
  §5). This is the standard generated-file-is-up-to-date gate — `go generate` then `git diff
  --exit-code`, Bazel's `diff_test`, `make -q` — regenerate into a scratch directory and
  byte-compare. The negative control below is the guard replaying what it is built for: one
  count edited by hand, and the message that names it.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))

import report_traceability as RT                                     # noqa: E402
from kg.extraction.grounding import is_grounded                      # noqa: E402

FRAMEWORK = REPO / "framework" / "ai_readiness_framework.json"
SKELETON = REPO / "docs" / "crosswalk" / "usafacts_operationalization_skeleton.md"
PUB = yaml.safe_load((REPO / "docs" / "reports" / "publication.yaml").read_text(encoding="utf-8"))

#: The documents G4's `EVIDENCED_BY` edges name. Typed here as the SUBJECT of the test —
#: "these are the ones the report quotes" — and asserted against the record below, so a source
#: added to the cell fails here rather than going uncited. Two until 2026-09-21;
#: `cc_tasks/2026-09-21_g4_resourcing_reissue.md` added the six standards that define G4's
#: fields and the DCAT-AP vocabulary it admitted for the statutory-mandate clause.
G4_DOCS = ("statistical-policy-working-paper-46-data-quality-assessment",
           "fcsm-19-01-transparent-reporting-for-integrated-data-quality",
           "dcat-us-1-1-schema", "dcat-us-3-dataset-schema", "dcat-us-3-overview",
           "w3c-dcat-3", "w3c-prov-o-ontology", "schema-org-dataset",
           "dcat-ap-3-0-0-r5r-vocabulary")

#: Decision 2 outcome (c), in the cell's own words. A clause with no passage behind it says so.
NO_PINPOINT = "general support; no pinpoint"

#: Every rendering of a corpus document that can be on disk, in preference order, with the
#: command that rebuilds it. Both are gitignored projections of the admitted bytes.
DOCLING = REPO / "state" / "docling_md"
BULK_PDF = REPO / "corpus" / "bulk"
#: The admission gate's converted substrate for HTML and markdown documents (DD-030,
#: `kg.ingest.gate.substrate_path`), and the manifest's canonical path when that is itself
#: markdown. The six standards added on 2026-09-21 are HTML or markdown, not PDF, so neither
#: rendering above exists for them.
SUBSTRATE = REPO / "state" / "substrate_md"
MANIFEST = REPO / "corpus" / "manifest.json"
REBUILD = ("/opt/anaconda3/bin/python3 scripts/t1_build_index.py --phase convert "
           "(Docling substrate), /opt/anaconda3/bin/python3 -m kg.ingest.gate --doc <doc_id> "
           "--no-task (HTML substrate), or re-acquire the PDF through "
           "scripts/fetch_allowlisted.py")


def indicator(code: str) -> dict:
    g = json.loads(FRAMEWORK.read_text(encoding="utf-8"))
    for n in g["nodes"]:
        if n.get("id") == f"ind:{code}":
            return n["properties"]
    raise AssertionError(f"the framework of record holds no ind:{code}")


def renderings(doc_id: str) -> dict:
    """`{rendering name: text}` for every rendering of `doc_id` on disk. Empty when none is."""
    out = {}
    md = DOCLING / f"{doc_id}.md"
    if md.is_file():
        out["docling_md"] = md.read_text(encoding="utf-8")
    sub = SUBSTRATE / f"{doc_id}.md"
    if sub.is_file():
        out["substrate_md"] = sub.read_text(encoding="utf-8")
    canon = ((json.loads(MANIFEST.read_text(encoding="utf-8"))["entries"].get(doc_id) or {})
             .get("identity") or {}).get("canonical_path") or ""
    if canon.endswith(".md") and (REPO / canon).is_file():
        out["canonical_md"] = (REPO / canon).read_text(encoding="utf-8")
    pdf = BULK_PDF / f"{doc_id}.pdf"
    if pdf.is_file():
        try:
            from pypdf import PdfReader
        except ImportError:                     # the suite runs on stdlib + pyyaml (CLAUDE.md)
            return out
        out["pypdf"] = "\n".join((p.extract_text() or "") for p in PdfReader(str(pdf)).pages)
    return out


def quoted_spans(locator: str) -> list:
    """The double-quoted verbatim spans in a locator parenthetical, in order."""
    return [s for s in re.findall(r'"([^"]+)"', locator) if s.strip()]


# ------------------------------------------------------------------ decisions 1 to 3
def test_the_record_and_the_skeleton_carry_the_same_g4_evidence_cell():
    """`build_framework_graph.py` through `framework_writeback.save` is the only path from the
    authored cell to the record. If the two disagree, the edit was made somewhere else or the
    projection step was skipped, and every assertion below is about a string nobody published."""
    cell = indicator("G4")["evidence_raw"]
    rows = [ln for ln in SKELETON.read_text(encoding="utf-8").splitlines()
            if re.match(r"^\|\s*G4\s*\|", ln)]
    assert len(rows) == 1, f"expected one G4 row in the skeleton, found {len(rows)}"
    assert cell in rows[0], (
        "the skeleton's G4 Evidence cell is not the record's `evidence_raw`; run "
        "scripts/build_framework_graph.py, which hands the result to framework_writeback.save")


def test_g4_names_exactly_the_two_documents_its_edges_name():
    locs = RT.locators(indicator("G4")["evidence_raw"])
    assert set(locs) == set(G4_DOCS), sorted(locs)
    g = json.loads(FRAMEWORK.read_text(encoding="utf-8"))
    edged = {e["properties"]["doc_id"] for e in g["edges"]
             if e["type"] == "EVIDENCED_BY" and e["from"] == "ind:G4"}
    assert edged == set(G4_DOCS), sorted(edged)


@pytest.mark.parametrize("doc_id", G4_DOCS)
def test_each_g4_source_carries_a_locator_or_says_it_has_none(doc_id):
    """The failure this exists for: a Source column filled and a Locator column empty. Decision
    2 makes three outcomes legal and the third — no passage supports the construct — is stated
    in words, so the only thing that cannot happen is silence."""
    loc = RT.locators(indicator("G4")["evidence_raw"])[doc_id]
    assert loc.strip(), (
        f"{doc_id} is cited on G4 with no locator: the appendix would print a source with no "
        f"place in it. Decision 2 of cc_tasks/2026-09-19_g4_locators_and_progress_drift.md")
    assert quoted_spans(loc) or NO_PINPOINT in loc, (
        f"{doc_id}'s locator carries neither a verbatim quoted span nor the words "
        f"'{NO_PINPOINT}': {loc[:200]}")


@pytest.mark.parametrize("doc_id", G4_DOCS)
def test_every_quoted_span_in_g4s_locator_is_verbatim_from_that_document(doc_id):
    """Invariant 3 applied to an evidence cell: no grounding span, no write. The quote is read
    from the record, not typed here, so editing the published cell is what this test guards."""
    spans = quoted_spans(RT.locators(indicator("G4")["evidence_raw"])[doc_id])
    assert spans, f"{doc_id} carries no quoted span; the outcome-(c) case is the test above"
    have = renderings(doc_id)
    if not have:
        pytest.skip(f"no rendering of {doc_id} on disk (both are gitignored); rebuild: {REBUILD}")
    bad = []
    for span in spans:
        per = {name: is_grounded(span, text) for name, text in have.items()}
        if not any(per.values()):
            bad.append((span[:80], per))
    assert not bad, (
        f"{doc_id}: {len(bad)} span(s) are in no rendering of the document on disk "
        f"({sorted(have)}). A locator is never written to make the appendix look complete: "
        f"{bad}")


def test_the_appendix_prints_g4s_locators_for_both_rows():
    """The cell is the authored source; this is the published consumer. If the appendix reads
    the locator from somewhere else, this fails and the RESULT says where instead."""
    fragment = REPO / "docs" / "reports" / "generated" / "sources_per_check.md"
    if not fragment.is_file():
        pytest.skip("the appendix fragment has not been built; run scripts/build_l0_report.py")
    rows = [ln for ln in fragment.read_text(encoding="utf-8").splitlines()
            if ln.startswith("| G4 |")]
    assert len(rows) == len(G4_DOCS), (
        f"expected {len(G4_DOCS)} G4 rows in the appendix, found {len(rows)}")
    locs = RT.locators(indicator("G4")["evidence_raw"])
    for doc_id, locator in locs.items():
        row = next((r for r in rows if doc_id in r), None)
        assert row, f"the appendix has no G4 row for {doc_id}"
        probe = quoted_spans(locator)[:1] or [NO_PINPOINT]
        assert probe[0][:60] in row, (
            f"the appendix's G4 row for {doc_id} does not carry the cell's locator; rebuild "
            f"with scripts/build_l0_report.py")


# ------------------------------------------------------------------ decision 4
REGEN_CMD = ("/opt/anaconda3/bin/python3 scripts/framework_progress.py --cycle "
             f"{PUB['snapshot_cycle']}")
PROGRESS = REPO / "docs" / "progress"
PROGRESS_FILES = ("framework_progress_2026-09-06.json", "index.html")


def first_difference(committed: str, regenerated: str, name: str) -> str | None:
    """The message a byte comparison owes its reader: which file, which line, both sides of it,
    and the one command that makes the committed copy current again. `None` when equal."""
    if committed == regenerated:
        return None
    a, b = committed.splitlines(), regenerated.splitlines()
    for i, (x, y) in enumerate(zip(a, b), start=1):
        if x != y:
            return (f"docs/progress/{name} is not what the generator produces today.\n"
                    f"  first differing line {i}\n"
                    f"    committed:   {x[:300]}\n"
                    f"    regenerated: {y[:300]}\n"
                    f"  regenerate with: {REGEN_CMD}")
    longer, side = (b, "regenerated") if len(b) > len(a) else (a, "committed")
    return (f"docs/progress/{name} is not what the generator produces today.\n"
            f"  the files agree for {min(len(a), len(b))} lines; the {side} copy has "
            f"{len(longer)} and the other ends first\n"
            f"    first extra line: {longer[min(len(a), len(b))][:300]}\n"
            f"  regenerate with: {REGEN_CMD}")


def regenerate(out_dir: Path) -> dict:
    """Run the page generator for the cycle of record into `out_dir`. The module's output paths
    are globals read at call time — this repo's convention, so a test can redirect them without
    the generator learning about tests (CLAUDE.md, "Conventions specific to this repo")."""
    import framework_progress as FP
    saved = (FP.OUT_JSON, FP.OUT_HTML, FP.DRAW_CYCLE)
    try:
        FP.OUT_JSON = out_dir / PROGRESS_FILES[0]
        FP.OUT_HTML = out_dir / PROGRESS_FILES[1]
        rc = FP.main(["--cycle", PUB["snapshot_cycle"]])
        assert rc == 0, f"the generator exited {rc}"
    finally:
        FP.OUT_JSON, FP.OUT_HTML, FP.DRAW_CYCLE = saved
    return {n: (out_dir / n).read_text(encoding="utf-8") for n in PROGRESS_FILES}


@pytest.fixture(scope="module")
def regenerated(tmp_path_factory) -> dict:
    return regenerate(tmp_path_factory.mktemp("progress"))


@pytest.mark.parametrize("name", PROGRESS_FILES)
def test_the_committed_progress_page_is_what_the_generator_produces_today(name, regenerated):
    committed = (PROGRESS / name).read_text(encoding="utf-8")
    msg = first_difference(committed, regenerated[name], name)
    assert msg is None, msg


def test_the_generator_is_deterministic_across_two_runs(tmp_path):
    """Decision 4's precondition. A byte comparison against a generator that stamps a clock or
    iterates a set would be a test that fails for the wrong reason, and the fix belongs in the
    generator rather than in an exemption here."""
    a = regenerate(tmp_path / "one")
    b = regenerate(tmp_path / "two")
    for name in PROGRESS_FILES:
        assert first_difference(a[name], b[name], name) is None


def test_the_drift_guard_reports_the_drift_it_was_built_for(tmp_path, regenerated):
    """The negative control, as a standing test rather than a paragraph in a RESULT: one count
    edited by hand in a scratch copy, and the message that names the line."""
    name = PROGRESS_FILES[0]
    page = json.loads(regenerated[name])
    before = page["whole"]["indicators"]
    hand_edited = regenerated[name].replace(f'"indicators": {before},',
                                            f'"indicators": {before + 1},', 1)
    assert hand_edited != regenerated[name], "the hand edit changed nothing; fix the control"
    msg = first_difference(hand_edited, regenerated[name], name)
    assert msg and f'"indicators": {before + 1}' in msg and f'"indicators": {before}' in msg, msg
    assert "regenerate with: " in msg and "framework_progress.py" in msg, msg
