#!/usr/bin/env python3
"""Generate `docs/design/mcp_over_the_graph.md` BY RUNNING THE TOOLS. **Zero spend.**

`cc_tasks/2026-09-17_mcp_over_the_graph.md` decision 4: "the tool list with one example call
and its actual output each, **generated by running the tools, not typed**."

A page of hand-written example outputs is a page that is wrong the first time a field is
renamed, and nothing says so. Here the outputs are the server's, captured at generation time,
and `--check` re-generates into memory and compares — so the page is either what the tools
answer today or the check is red. That is the same discipline
`scripts/build_framework_graph.py --dry-run` gives the framework record.

    /opt/anaconda3/bin/python3 mcp/airkg_doc.py            # write the page
    /opt/anaconda3/bin/python3 mcp/airkg_doc.py --check    # is the page on disk what the
                                                           # tools answer? exit 1 if not
Requires Neo4j: a page generated without the database would document eight tools answering
"Neo4j unreachable", which is not what the server does.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MCP_DIR = Path(__file__).resolve().parent
REPO = MCP_DIR.parent
sys.path.insert(0, str(MCP_DIR))

import airkg_server as S   # noqa: E402
import airkg_tools as T    # noqa: E402

PAGE = REPO / "docs" / "design" / "mcp_over_the_graph.md"
TASK = "cc_tasks/2026-09-17_mcp_over_the_graph.md"

#: How much of an answer the page shows. A full `get_prescriptions()` is 45 actions with their
#: quotes; printing it would bury the shape it is there to show. Every excerpt says in words
#: what was cut and the full answer is one call away — what is NEVER cut is the locators, which
#: are the point.
MAX_LIST = 2

#: The title's count, spelled, derived from `TOOL_ORDER` so a tenth tool cannot leave the page
#: saying nine.
_NUMBER = {9: "nine", 10: "ten", 11: "eleven", 12: "twelve"}


def _trim(value, depth: int = 0):
    """Long lists to their first `MAX_LIST` entries plus a marker naming what was dropped.
    Applied to every list in an answer except a list of locators, which is shown whole."""
    if isinstance(value, dict):
        return {k: (v if k in ("locators", "locator") else _trim(v, depth + 1))
                for k, v in value.items()}
    if isinstance(value, list):
        if len(value) <= MAX_LIST:
            return [_trim(v, depth + 1) for v in value]
        return [_trim(v, depth + 1) for v in value[:MAX_LIST]] + [
            f"… {len(value) - MAX_LIST} more (elided by mcp/airkg_doc.py, not by the tool)"]
    if isinstance(value, str) and len(value) > 320:
        return value[:320] + f"… [{len(value)} chars]"
    return value


def examples(tools: T.Tools) -> list:
    """One real call per tool, in `TOOL_ORDER`. The arguments are chosen to show the shape a
    client actually uses: an indicator that has actions, a body that fails legs, a Finding id
    taken from the body call above it."""
    body_name = "NCHS"
    body = tools.get_body(body_name)
    finding_id = body["legs"][0]["finding_id"]
    calls = [
        ("get_overview", {}, tools.get_overview),
        ("get_indicator", {"code": "A5"}, lambda: tools.get_indicator("A5")),
        ("get_body", {"name": body_name}, lambda: body),
        ("get_prescriptions", {"body": body_name},
         lambda: tools.get_prescriptions(body=body_name)),
        ("get_requirements", {"indicator": "C4"},
         lambda: tools.get_requirements(indicator="C4")),
        ("get_evidence", {"finding_id": finding_id},
         lambda: tools.get_evidence(finding_id)),
        ("get_document", {"doc_id": "rfc-9309-robots-exclusion-protocol"},
         lambda: tools.get_document("rfc-9309-robots-exclusion-protocol")),
        ("search_text", {"q": "sitemap", "limit": 3},
         lambda: tools.search_text("sitemap", limit=3)),
        ("get_cycle_of_record", {}, tools.get_cycle_of_record),
        ("run_cypher", {"query": "MATCH (r:Rule {current: true}) RETURN count(r) AS current_rules"},
         lambda: tools.run_cypher(
             "MATCH (r:Rule {current: true}) RETURN count(r) AS current_rules")),
    ]
    assert tuple(c[0] for c in calls) == T.TOOL_ORDER, "a tool has no example call"
    return [(name, args, fn()) for name, args, fn in calls]


def _doc_of(mcp, name: str) -> str:
    """The tool's own description, as the client sees it — never a second copy written here."""
    tool = mcp._tool_manager._tools[name] if hasattr(mcp, "_tool_manager") else None
    text = (tool.description if tool is not None else "") or ""
    return text.strip()


def render(mcp, tools: T.Tools) -> str:
    rows = examples(tools)
    gate = tools.get_overview()["projection_gate"]
    out = []
    w = out.append
    w(f"# The graph through an MCP: {_NUMBER[len(T.TOOL_ORDER)]} read-only tools, every "
      f"answer with its locator")
    w("")
    w(f"**Generated** by `mcp/airkg_doc.py` from `{TASK}` (decision 4), by RUNNING the tools "
      f"against the live database. Nothing on this page is typed: re-run "
      f"`/opt/anaconda3/bin/python3 mcp/airkg_doc.py --check` and it fails if the page and the "
      f"server have drifted.")
    w("")
    w("## What it is")
    w("")
    w(S.INSTRUCTIONS.strip())
    w("")
    w("## Running it")
    w("")
    w("```bash")
    w("/opt/anaconda3/bin/python3 mcp/airkg_server.py            # stdio, the project database")
    w("/opt/anaconda3/bin/python3 mcp/airkg_server.py --no-graph # record-only, no Neo4j")
    w("```")
    w("")
    w("Claude Code reads `.mcp.json` in this repository and needs nothing else. For Claude "
      "Desktop the same object goes in `~/Library/Application Support/Claude/"
      "claude_desktop_config.json` under `mcpServers`; the exact lines are in the task's "
      "RESULT §3.")
    w("")
    w(f"The interpreter is named explicitly because `fastmcp`, the Neo4j driver and `pyyaml` "
      f"are installed in `/opt/anaconda3/bin/python3` — the same interpreter `CLAUDE.md` names "
      f"for extraction and projection.")
    w("")
    w("## The rails")
    w("")
    w("| rail | what it does | where |")
    w("|---|---|---|")
    w("| one database | an allow-list of exactly one name, read from `seldon.yaml:neo4j."
      "database`; every other name is `SystemExit` at startup | `mcp/airkg_guard.py::"
      "assert_allowed_db` |")
    w("| read-only, belt 1 | write clauses and unlisted `CALL` procedures are refused before "
      "anything reaches the database, with the refusal RETURNED as a message | "
      "`mcp/airkg_guard.py::refusal` |")
    w("| read-only, belt 2 | every statement runs in the driver's explicit read transaction | "
      "`mcp/airkg_tools.py::Graph.read` |")
    w("| flood cap | 200 rows | `mcp/airkg_guard.py::MAX_ROWS` |")
    w("")
    w("## The projection gate, at generation time")
    w("")
    w(f"`{gate['status']}` — {gate['reason']} ({gate['nodes_compared']} nodes compared against "
      f"`framework/ai_readiness_framework.json`, cell for cell). `get_overview` recomputes this "
      f"on every call and `run_cypher` returns it beside every result, because DD-057 makes a "
      f"Cypher answer over the framework labels valid only while it is green.")
    w("")
    w("## The tools")
    w("")
    w(f"One real call each, with the answer the tool gave. Long lists are cut to "
      f"{MAX_LIST} entries by the generator, which says so in place; **locator lists are never "
      f"cut**.")
    for name, args, answer in rows:
        w("")
        w(f"### `{name}({', '.join(f'{k}={v!r}' for k, v in args.items())})`")
        w("")
        w(_doc_of(mcp, name))
        w("")
        w("```json")
        w(json.dumps(_trim(answer), indent=2, ensure_ascii=False, default=str))
        w("```")
    w("")
    w("## What this page is not")
    w("")
    w("It is not the framework and it is not a view of it (DN-005 §5 rule 2): it is the "
      "exposure layer's documentation. The framework record, the matrices and the retained "
      "response bodies are the things; this server is one interface onto them, and the "
      "locators on every answer are what let a reader leave the interface and check the thing.")
    w("")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare the page on disk with what the tools answer now; exit 1 on "
                         "any difference")
    a = ap.parse_args(argv)
    graph = T.Graph()
    if not graph.available():
        raise SystemExit(f"FATAL: Neo4j unreachable ({graph.error}); a page generated without "
                         f"the database would document tools that cannot answer")
    mcp, tools = S.create_server(graph=graph)
    text = render(mcp, tools)
    if a.check:
        if not PAGE.exists():
            print(f"FAIL {PAGE.relative_to(REPO)} does not exist")
            return 1
        on_disk = PAGE.read_text(encoding="utf-8")
        if on_disk != text:
            import difflib
            diff = list(difflib.unified_diff(on_disk.splitlines(), text.splitlines(),
                                             "on disk", "generated now", lineterm=""))
            print(f"FAIL the page and the tools have drifted ({len(diff)} diff lines)")
            print("\n".join(diff[:40]))
            return 1
        print(f"   {PAGE.relative_to(REPO)}: generated content, byte-for-byte")
        return 0
    PAGE.write_text(text, encoding="utf-8")
    print(f"-> {PAGE.relative_to(REPO)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
