#!/usr/bin/env python3
"""The requirements and install section of `docs/adopt/run_on_your_site.md`, generated from
`pyproject.toml`, so the runbook and the install it describes cannot drift.

`cc_tasks/2026-10-07_install_closure_v2.md` decision 4. The section between the two markers is
a VIEW of `pyproject.toml` (`requires-python`, `dependencies`, the `graph` and `mcp` extras)
and of `seldon.yaml` (the database the projection writes to). Nothing in it is typed by hand.

    python3 scripts/build_adopt_requirements.py           rewrite the section in place
    python3 scripts/build_adopt_requirements.py --check   regenerate in memory; exit 1 on drift

The import check in the section names the modules each runtime distribution provides. That
mapping is read from the interpreter running the generator (`importlib.metadata`), which is why
the generator refuses when a declared runtime distribution is not installed in it: a guessed
module name is the drift this file exists to stop.

**Idempotence.** Nothing reads a clock; the order is the order of `pyproject.toml`.
"""
from __future__ import annotations

import argparse
import importlib.metadata
import re
import sys
import tomllib
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
PYPROJECT = REPO / "pyproject.toml"
SELDON_YAML = REPO / "seldon.yaml"
RUNBOOK = REPO / "docs" / "adopt" / "run_on_your_site.md"
BEGIN = ("<!-- BEGIN generated by scripts/build_adopt_requirements.py from pyproject.toml and "
         "seldon.yaml. Do not edit: re-run the generator. -->")
END = "<!-- END generated by scripts/build_adopt_requirements.py -->"
#: `name==version` or `name @ url@commit`, the only two forms pyproject.toml declares.
PIN = re.compile(r"^(?P<name>[A-Za-z0-9._-]+)(?:==(?P<version>[^\s;]+)| @ (?P<url>\S+))$")


def _pins(reqs: list) -> list:
    out = []
    for r in reqs:
        m = PIN.match(r.strip())
        if not m:
            raise SystemExit(f"REFUSING: {r!r} in {PYPROJECT.name} is neither pinned with == nor "
                             f"a URL at a commit (cc_tasks/2026-10-07_install_closure_v2.md "
                             f"decision 1 pins every dependency)")
        out.append(m.groupdict())
    return out


def _modules(dist: str) -> list:
    """The top-level import names a distribution provides, from the generating interpreter."""
    by_module = importlib.metadata.packages_distributions()
    want = {dist.lower().replace("_", "-")}
    mods = sorted({m for m, ds in by_module.items()
                   if any(d.lower().replace("_", "-") in want for d in ds)
                   and not m.startswith("_") and m.isidentifier()})
    if not mods:
        raise SystemExit(f"REFUSING: runtime dependency {dist!r} is not installed in "
                         f"{sys.executable}, so the module it provides cannot be read. Install "
                         f"pyproject.toml's dependencies into this interpreter and re-run.")
    return mods


def _short(url: str) -> str:
    repo, _, commit = url.removeprefix("git+").rpartition("@")
    return f"{repo.removesuffix('.git')} at `{commit[:12]}`"


def render() -> str:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))["project"]
    runtime = _pins(project["dependencies"])
    extras = project["optional-dependencies"]
    graph, mcp = _pins(extras["graph"]), _pins(extras["mcp"])
    database = yaml.safe_load(SELDON_YAML.read_text(encoding="utf-8"))["neo4j"]["database"]
    imports = []
    for p in runtime:
        # PyYAML also ships `_yaml`; extruct, rdflib and the rest one name each. A distribution
        # that provides several importable names contributes the one named like itself, else all.
        mods = _modules(p["name"])
        same = [m for m in mods if m.lower() == p["name"].lower()]
        imports += same or mods
    listed = ", ".join(f"`{p['name']}` {p['version']}" for p in runtime)

    def extra(pins: list) -> str:
        return ", ".join(f"`{p['name']}` {p['version']}" if p["version"]
                         else f"`{p['name']}` from {_short(p['url'])}" for p in pins)

    return "\n".join([
        BEGIN,
        "",
        f"* **Python {project['requires-python']}** (`requires-python` in `pyproject.toml`).",
        f"* **The {len(runtime)} packages `pip install .` installs**, the `dependencies` of "
        f"`pyproject.toml`. These are the third-party modules the scan and the report import, "
        f"and the gate checks the list against the imports the run actually loaded. Versions "
        f"are the ones the gate ran under:",
        f"  {listed}.",
        "* **`make`**, **`git`** and **`bash`**.",
        f"* **Optional: Neo4j**, if you want graph answers (step 7). `pip install '.[graph]'` "
        f"adds {extra(graph)}. The server is a Neo4j 5 instance holding a database named "
        f"`{database}` (`seldon.yaml`, `neo4j.database`); creating a database by that name "
        f"needs an edition that can create one, or the server's default database renamed to it. "
        f"The address comes from `NEO4J_URI` (default `bolt://localhost:7687`) and the "
        f"credentials from `NEO4J_USER` and `NEO4J_PASS`.",
        f"* **Optional: the MCP server**, if you want to connect a client to it. "
        f"`pip install '.[mcp]'` adds {extra(mcp)}.",
        "* **Your own identity for the scanner** (step 2). A scan that reaches any host other "
        "than your own machine will not run without one.",
        "",
        "## 1. Get the code (not run by the gate: needs the network)",
        "",
        "```bash not-run-by-gate",
        "git clone https://github.com/brockwebb/ai-readiness-kg.git",
        "cd ai-readiness-kg",
        "python3 -m venv .venv",
        ". .venv/bin/activate",
        "python3 -m pip install .",
        "```",
        "",
        "Two gates run this page. `test_a_stranger_installs_and_runs_the_runbook` takes a "
        "`git archive` of the committed HEAD (no untracked file, no ignored file), runs the "
        "last three lines of the block above in it word for word, with `HOME` set to an empty "
        "scratch directory and a `PATH` that holds the new virtual environment and the system's "
        "`/usr/bin` and `/bin` and nothing else, then runs every block below. "
        "`test_the_runbook_runs_as_written` runs every block below on the author's interpreter, "
        "in a copy of the working tree.",
        "",
        "Tell `make` which Python to use, and check that it has the packages:",
        "",
        "```bash",
        'export PY="$(command -v python3)"',
        f"\"$PY\" -c 'import {', '.join(imports)}; print(\"requirements OK\")'",
        "```",
        "",
        END,
    ])


def splice(text: str, section: str) -> str:
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise SystemExit(f"REFUSING: {RUNBOOK.relative_to(REPO)} must hold each marker exactly "
                         f"once:\n  {BEGIN}\n  {END}")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + section + tail


def main(argv: list | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="regenerate in memory and exit 1 if the runbook differs")
    args = ap.parse_args(argv)
    text = RUNBOOK.read_text(encoding="utf-8")
    new = splice(text, render())
    if args.check:
        if new != text:
            print(f"DRIFT: {RUNBOOK.relative_to(REPO)} does not match pyproject.toml; run "
                  f"scripts/build_adopt_requirements.py", file=sys.stderr)
            return 1
        print(f"OK: {RUNBOOK.relative_to(REPO)} matches pyproject.toml")
        return 0
    if new != text:
        RUNBOOK.write_text(new, encoding="utf-8")
        print(f"wrote {RUNBOOK.relative_to(REPO)}")
    else:
        print(f"unchanged: {RUNBOOK.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
