#!/usr/bin/env bash
. "$(dirname "$0")/check_protected_lib.sh"
# The write set of `cc_tasks/2026-09-19_resnapshot_rj4.md`, asserted against HEAD.
#
#   "docs/reports/publication.yaml, the report and its generated fragments, the PDF, docs/data/*
#    and the manifest through build_l0_site.py, results_tagged.json and the Results ledger
#    (promotions), framework/ai_readiness_framework.json through the writer (decision 2),
#    scripts/snapshot_successor.py and scripts/score.py and mcp/ (decisions 3, 4), the shard
#    (decision 5 overlay, append), the corpus events (decision 6), the projection, tests for 3 to
#    6, scripts/check_protected_resnapshot.sh (new), seldon_events.jsonl, the RESULT. No
#    Observation, no Finding, no matrix content changes."
#
# Paths the write set does not name, each reported in the RESULT §4 with its reason, each listed
# in ALLOWED below and nowhere else:
#
#   * scan/publish.py: `finding_withdrawn` is a new event type and the projection had to read it
#     (decision 5). scan/figures.py, figures.yaml, scripts/register_figure_results.py: F5 for the
#     new snapshot, and B5 (a body leg) has no per-surface rate. The six `_rj4` SVGs are new.
#   * scripts/build_l0_matrices.py (the snapshot read from its fixed home, not OUT_DIR),
#     scripts/rederive_tagged_results.py (the snapshot read, not typed),
#     scripts/publish_result_states.py (a Result already published is beyond `verify`),
#     scripts/register_l0_report_results.py (no socket count under a re-judgement's name).
#   * four new scripts: withdraw_rj3_g1d_findings.py, emit_tool_doc_manifest_adds.py,
#     backfill_g4_source_metadata.py, supersede_rj2_published_results.py.
#   * corpus/manifest.json and corpus/evidence/decisions.jsonl: two `metadata_corrected` events
#     for G4's two sources, which the appendix now cites (DN-001's citability floor).
#   * events/batch-024.jsonl: `manifest.add`'s admission gate (DD-030) converts what it admits.
#   * state/: the `_rj4` report matrices `scan_report --cycle` writes, and the re-derivation
#     record. docs/design/scoring_model.md and mcp_over_the_graph.md: generated views.
#   * docs/progress/: the progress page is a view of the cycle of record
#     (`tests/test_scan_run_2.py`), regenerated by `scripts/framework_progress.py --cycle`;
#     it had also drifted from the framework record since 2026-09-11.
#   * tests: eight existing files whose pins named the old snapshot, the fixed ten columns or
#     a matrix column with no per-surface rate.
set -u
cd "$(dirname "$0")/.." || exit 2
fail=0
PY=/opt/anaconda3/bin/python3

changed_and_new() {
  { git diff --name-only HEAD -- "$@"; git ls-files --others --exclude-standard -- "$@"; } \
    | sed '/^$/d' | sort -u
}

# 1. Byte-identical outright: the instrument, the matrices, every stored payload.
for p in 'kg/' 'assessment/harness/scan/rules/' 'assessment/harness/scan/params.yaml' \
         'assessment/harness/scan/runner.py' 'assessment/harness/scan/manners.py' \
         'assessment/harness/scan/model.py' 'assessment/harness/scan/rederive.py' \
         'assessment/harness/scan/collectors/' 'assessment/harness/scan/fixtures/' \
         'docs/reports/scan_matrix_' 'docs/crosswalk/' 'docs/research/' \
         'controls.yaml' 'dixie_evidence.yaml' 'seldon.yaml' 'cc_tasks/'; do
  moved=$(changed_and_new "$p")
  if [ -n "$moved" ]; then
    echo "FAIL protected path moved: $p"; echo "$moved" | sed 's/^/       /'; fail=1
  fi
done
if [ -n "$(git diff --name-only HEAD -- 'docs/reports/scan_matrix_*')" ]; then
  echo "FAIL a published matrix changed content"; fail=1
fi

# 2. state/: three new files, no tracked payload modified.
moved=$(changed_and_new 'state/')
want=$(printf '%s\n' state/rederive_tagged_2026-09-19.json state/scan_matrix_2026-09-10_rj4.json \
       state/scan_matrix_tierc_2026-09-10_rj4.json | sort)
if [ "$moved" != "$want" ]; then
  echo "FAIL state/ moved other than the two rj4 report matrices and the re-derivation record:"
  echo "$moved" | sed 's/^/       /'; fail=1
fi

# 3. events/: no new shard; every committed shard a byte prefix of what is on disk; exactly four
#    shards appended to, each with exactly the lines and event types this task writes.
new_shards=$(git ls-files --others --exclude-standard -- events/)
if [ -n "$new_shards" ]; then
  echo "FAIL events/ gained a shard:"; echo "$new_shards" | sed 's/^/       /'; fail=1
fi
"$PY" - <<'PYEOF' || fail=1
import json, subprocess, sys
from pathlib import Path
want = {"events/batch-001.jsonl": {"manifest_add": 2},
        "events/batch-024.jsonl": {"substrate_converted": 2},
        "events/batch-033_framework.jsonl": {"framework_writeback": 1},
        "events/cycle-scan_2026-09-10_rj3.jsonl": {"finding_withdrawn": 22}}
tracked = [r for r in subprocess.run(["git", "ls-files", "events/"], capture_output=True,
                                     text=True).stdout.split() if r.endswith(".jsonl")]
bad, grew = [], {}
for rel in tracked:
    was = subprocess.run(["git", "show", f"HEAD:{rel}"], capture_output=True).stdout
    now = Path(rel).read_bytes()
    if not now.startswith(was):
        bad.append(rel)
    elif len(now) > len(was):
        kinds = {}
        for line in now[len(was):].decode("utf-8").splitlines():
            t = json.loads(line)["event_type"]
            kinds[t] = kinds.get(t, 0) + 1
        grew[rel] = kinds
print(f"   events/: {len(tracked)} tracked shard(s); appended {grew}; rewritten {bad}")
if bad or grew != want:
    print(f"FAIL events/: want exactly {want}")
    sys.exit(1)
PYEOF

# 4. corpus/: the ledger projection and the ledger, the ledger append-only by two corrections.
moved=$(changed_and_new 'corpus/')
if [ "$moved" != "$(printf '%s\n' corpus/evidence/decisions.jsonl corpus/manifest.json)" ]; then
  echo "FAIL corpus/ moved other than the ledger and its projection:"
  echo "$moved" | sed 's/^/       /'; fail=1
fi
"$PY" - <<'PYEOF' || fail=1
import json, subprocess, sys
from pathlib import Path
rel = "corpus/evidence/decisions.jsonl"
was = subprocess.run(["git", "show", f"HEAD:{rel}"], capture_output=True).stdout
now = Path(rel).read_bytes()
new = now[len(was):].decode("utf-8").splitlines() if now.startswith(was) else None
ok = new is not None and len(new) == 2 and all(
    json.loads(l).get("event_type") == "metadata_corrected" for l in new)
print(f"   {rel}: {'append-only, ' + str(len(new)) + ' new line(s)' if new is not None else 'REWRITTEN'}")
sys.exit(0 if ok else 1)
PYEOF

# 5. Every path that moved is on the list.
ALLOWED=(
  '.zenodo.json' 'CITATION.cff'
  'assessment/harness/scan/figures.py' 'assessment/harness/scan/figures.yaml'
  'assessment/harness/scan/publish.py'
  'corpus/evidence/decisions.jsonl' 'corpus/manifest.json'
  'docs/data/CITATION.cff' 'docs/data/ai_readiness_framework.json'
  'docs/data/corpus_manifest.json' 'docs/data/index.json' 'docs/data/results_tagged.json'
  'docs/data/sources_per_check.json' 'docs/data/zenodo.json'
  'docs/design/mcp_over_the_graph.md' 'docs/design/scoring_model.md'
  'docs/index.html' 'docs/llms.txt' 'docs/sitemap.xml'
  'docs/progress/index.html' 'docs/progress/framework_progress_2026-09-06.json'
  'docs/reports/2026-09_fss_ai_readiness_L0.md' 'docs/reports/2026-09_fss_ai_readiness_L0.pdf'
  'docs/reports/generated/matrix_product.md' 'docs/reports/generated/rules_by_leg.md'
  'docs/reports/generated/sources_per_check.md' 'docs/reports/publication.yaml'
  'docs/reports/sections/10_frame.md' 'docs/reports/sections/20_matrix.md'
  'docs/reports/sections/30_refusals.md' 'docs/reports/sections/40_product.md'
  'docs/reports/sections/50_limits.md' 'docs/reports/sections/60_movement.md'
  'docs/reports/sections/80_appendix.md'
  'events/batch-001.jsonl' 'events/batch-024.jsonl' 'events/batch-033_framework.jsonl'
  'events/cycle-scan_2026-09-10_rj3.jsonl'
  'framework/ai_readiness_framework.json'
  'mcp/airkg_tools.py'
  'scripts/build_l0_matrices.py' 'scripts/publish_result_states.py'
  'scripts/rederive_tagged_results.py' 'scripts/register_figure_results.py'
  'scripts/register_l0_report_results.py' 'scripts/score.py' 'scripts/snapshot_successor.py'
  'scripts/check_protected_resnapshot.sh' 'scripts/withdraw_rj3_g1d_findings.py'
  'scripts/emit_tool_doc_manifest_adds.py' 'scripts/backfill_g4_source_metadata.py'
  'scripts/supersede_rj2_published_results.py'
  'state/rederive_tagged_2026-09-19.json' 'state/scan_matrix_2026-09-10_rj4.json'
  'state/scan_matrix_tierc_2026-09-10_rj4.json'
  'tests/test_mcp_server.py' 'tests/test_publication.py' 'tests/test_rejudge_seven_legs.py'
  'tests/test_report_figures_agree.py' 'tests/test_report_traceability.py'
  'tests/test_scan_figures.py' 'tests/test_snapshot_successor.py' 'tests/test_resnapshot_rj4.py'
  'tests/test_f5_membership.py'
  'cc_tasks/2026-09-19_resnapshot_rj4_RESULT.md'
)
while IFS= read -r path; do
  [ -z "$path" ] && continue
  case "$path" in
    assessment/harness/scan/figures/scan_2026-09-10_rj4/*.svg) continue ;;
  esac
  ok=0
  for a in "${ALLOWED[@]}"; do [ "$path" = "$a" ] && ok=1 && break; done
  if [ "$ok" = 0 ]; then echo "FAIL not in the write set: $path"; fail=1; fi
done < <({ git diff --name-only HEAD; git ls-files --others --exclude-standard; } | sort -u)

# 6. No figure of any earlier cycle moved: the rated-legs change draws exactly what it drew.
moved=$(git diff --name-only HEAD -- 'assessment/harness/scan/figures/')
if [ -n "$moved" ]; then
  echo "FAIL an earlier cycle's figure moved:"; echo "$moved" | sed 's/^/       /'; fail=1
fi

if [ "$fail" = 0 ]; then echo "PROTECTED PATHS OK"; fi
exit "$fail"
