#!/usr/bin/env bash
. "$(dirname "$0")/check_protected_lib.sh"
# The write set of `cc_tasks/2026-10-06_l0_report_robots_wording.md`, asserted against HEAD.
#
# A wording correction (audit C-02): two report section sources, the report builder's version
# block, the correction declared in `publication.yaml`, the rebuilt report (markdown and PDF), the
# prior snapshot kept beside it, one test, this check and the RESULT — and the brief pack's
# architecture page, whose locator for the report builder (`build_l0_report.py:<line>`) the
# builder's new function moved; it is regenerated by `scripts/build_brief_pack.py`, not edited.
# "Byte-identical: every rule, collector and matrix" — so nothing under the harness, no matrix,
# no generated fragment, no framework record and no event shard may move.
set -u
cd "$(dirname "$0")/.." || exit 2
fail=0

changed_and_new() {
  { git diff --name-only HEAD -- "$@"; git ls-files --others --exclude-standard -- "$@"; } \
    | sed '/^$/d' | sort -u
}

allowed() {
  case "$1" in
    docs/reports/sections/20_matrix.md|docs/reports/sections/30_refusals.md) return 0 ;;
    docs/reports/2026-09_fss_ai_readiness_L0.md|docs/reports/2026-09_fss_ai_readiness_L0.pdf) return 0 ;;
    docs/reports/publication.yaml|scripts/build_l0_report.py) return 0 ;;
    docs/reports/snapshots/2026-09_fss_ai_readiness_L0.688451fb.md) return 0 ;;
    docs/reports/snapshots/2026-09_fss_ai_readiness_L0.688451fb.pdf) return 0 ;;
    tests/test_robots_claims_match_matrix.py|scripts/check_protected_robots_wording.sh) return 0 ;;
    docs/brief/E_architecture.md) return 0 ;;
    cc_tasks/2026-10-06_l0_report_robots_wording_RESULT.md) return 0 ;;
  esac
  return 1
}

while IFS= read -r path; do
  [ -z "$path" ] && continue
  allowed "$path" || { echo "FAIL path outside the write set moved: $path"; fail=1; }
done < <(changed_and_new .)

# The kept snapshot is the text as published before the correction: byte-identical to the last
# commit that wrote the report (decision 3, "do not rewrite history").
for ext in md pdf; do
  kept="docs/reports/snapshots/2026-09_fss_ai_readiness_L0.688451fb.$ext"
  want=$(git show "688451fb:docs/reports/2026-09_fss_ai_readiness_L0.$ext" | shasum -a 256 | cut -d' ' -f1)
  got=$(shasum -a 256 "$kept" 2>/dev/null | cut -d' ' -f1)
  [ "$got" = "$want" ] || { echo "FAIL $kept is not the report as committed at 688451fb"; fail=1; }
done

# The Seldon store is append-only.
removed=$(git diff HEAD -- seldon_events.jsonl | grep -c '^-[^-]' || true)
if [ "$removed" -ne 0 ]; then echo "FAIL seldon_events.jsonl lost or changed $removed line(s)"; fail=1; fi

if [ "$fail" -eq 0 ]; then echo "PROTECTED PATHS: PASS"; else echo "PROTECTED PATHS: FAIL"; fi
exit "$fail"
