#!/usr/bin/env bash
. "$(dirname "$0")/check_protected_lib.sh"
# The zero-edits list of `cc_tasks/2026-09-12_publish_l0.md`, asserted against HEAD:
#
#   "Zero edits to: rule modules, harness runtime, stored payloads, cycle evidence, targets,
#    figures, section prose, the skeleton, the record, corpus/."
#
# Three of those are not path lists and are checked as themselves:
#
#   * The MATRICES and the report FRAGMENTS are regenerated by this task's re-derivation gate
#     (`scripts/rederive_tagged_results.py` drives `build_l0_matrices` over the snapshot cycle
#     for real, into the shipped paths). They are protected here, so "the generator reproduces
#     its own outputs byte-for-byte" is asserted rather than asserted-about: a re-derivation
#     that changed a published matrix would fail this script, not pass it quietly.
#   * `state/` may not be MODIFIED. It may gain exactly the files named in NEW_STATE below,
#     each of which is a file the graph already names and the repo did not hold.
#   * `events/` is untouched whole: this task writes to the SELDON log
#     (`seldon_events.jsonl`), which is append-only and is checked for deletions instead.
set -u
cd "$(dirname "$0")/.." || exit 2
PY=/opt/anaconda3/bin/python3
fail=0

# Byte-identical, and no new file inside them either.
protected=(
  'assessment/'
  'corpus/'
  'events/'
  'framework/'
  'docs/reports/sections/'
  'docs/reports/generated/'
  'docs/crosswalk/usafacts_operationalization_skeleton.md'
)
for p in "${protected[@]}"; do
  changed=$(git diff --name-only HEAD -- "$p"; git ls-files --others --exclude-standard -- "$p")
  if [ -n "$changed" ]; then
    echo "FAIL protected path moved: $p"
    echo "$changed" | sed 's/^/       /'
    fail=1
  fi
done

# The published matrices of the snapshot cycle: regenerated this session, and identical.
mx=$(git diff --name-only HEAD -- 'docs/reports/scan_matrix_*')
if [ -n "$mx" ]; then
  echo "FAIL a published matrix changed; the generator does not reproduce its own output:"
  echo "$mx" | sed 's/^/       /'; fail=1
fi

# Prior RESULTs are execution records and are never edited.
prior=$(git diff --name-only HEAD -- 'cc_tasks/*_RESULT.md')
if [ -n "$prior" ]; then
  echo "FAIL a prior RESULT changed:"; echo "$prior" | sed 's/^/       /'; fail=1
fi

# state/: no modification, and only the declared additions.
#
# `state/scan_matrix_2026-09-10.json` is NOT here and must not appear. The measured cycle was
# deliberately never reported — the judgement of record is the re-judgement `_rj2` — and
# `tests/test_scan_figures.py::matrix` skips the figure suite on exactly that absence
# (`cc_tasks/2026-09-10_harness_v5_blind.md` decision 6). This task materialised it once, by
# re-running the generator to re-derive four counts, and turned eight documented skips into
# eight errors. The re-derivation now writes that matrix to a temporary tree instead, and this
# list is where the mistake is prevented from recurring.
NEW_STATE=(
  'state/rederive_tagged_2026-09-12.json'
)
mod=$(git diff --name-only HEAD -- 'state/')
if [ -n "$mod" ]; then
  echo "FAIL a stored payload was MODIFIED:"; echo "$mod" | sed 's/^/       /'; fail=1
fi
while read -r f; do
  [ -z "$f" ] && continue
  ok=0
  for allowed in "${NEW_STATE[@]}"; do [ "$f" = "$allowed" ] && ok=1; done
  if [ "$ok" -eq 0 ]; then
    echo "FAIL an undeclared file appeared under state/: $f"; fail=1
  fi
done <<< "$(git ls-files --others --exclude-standard -- 'state/')"

# The Seldon event log is append-only: this task writes state transitions to it.
if git diff seldon_events.jsonl | grep -q '^-[^-]'; then
  echo "FAIL seldon_events.jsonl lost a line; the log is append-only"; fail=1
fi

if [ "$fail" -eq 0 ]; then
  echo "PASS  the harness, corpus/, events/, the record, the skeleton, section prose, the"
  echo "      report fragments and every published matrix are byte-identical to HEAD; state/"
  echo "      gained only the declared files and lost nothing; the Seldon log only grew"
fi

echo
echo "what DID change:"
{ git diff --name-only HEAD; git ls-files --others --exclude-standard; } | sort -u | sed 's/^/       /'
exit "$fail"
