#!/usr/bin/env bash
. "$(dirname "$0")/check_protected_lib.sh"
# The write set of `cc_tasks/2026-09-19_spot_scan.md`, asserted against HEAD.
#
#   "assessment/harness/scan/run.py, publish.py, rederive.py, build_l0_matrices.py (bodies
#    present), scripts/score.py, scripts/prescriptions.py, mcp/ (the three view changes),
#    docs/reports/build_report.py (the refusal), cc_tasks/templates/spot_scan.md (new), tests,
#    scripts/check_protected_spot.sh (new), seldon_events.jsonl, the RESULT. state/, corpus/,
#    docs/reports/ payloads: byte-identical."
#
# Paths the write set does not name, each reported in the RESULT §3 with its reason, each listed
# in ALLOWED below and nowhere else:
#
#   * assessment/harness/scan/spot.py (new): the one definition of what a spot cycle is, read by
#     the harness, the builders and the views, so no reader keeps a prefix test of its own.
#   * scripts/build_l0_report.py and scripts/build_l0_site.py: "docs/reports/build_report.py"
#     does not exist; these two are the builders that read `snapshot_cycle`, and both refuse.
#   * scripts/render_spot_scan.py (new): decision 4's render, because `seldon cadence render`
#     does not exist and Seldon's `render` refuses the two spot fields.
#   * docs/design/mcp_over_the_graph.md: generated by `mcp/airkg_doc.py`, whose `--check` test
#     is red until the page shows the new `cycles` and `latest_measurement` fields.
set -u
cd "$(dirname "$0")/.." || exit 2
fail=0

changed_and_new() {
  { git diff --name-only HEAD -- "$@"; git ls-files --others --exclude-standard -- "$@"; } \
    | sed '/^$/d' | sort -u
}

# 1. Byte-identical outright: the instrument, every stored payload, the corpus, the log, every
#    published matrix and the report tree, the framework record.
for p in 'kg/' 'assessment/harness/scan/rules/' 'assessment/harness/scan/params.yaml' \
         'assessment/harness/scan/runner.py' 'assessment/harness/scan/manners.py' \
         'assessment/harness/scan/model.py' 'assessment/harness/scan/collectors/' \
         'assessment/harness/scan/fixtures/' 'assessment/harness/scan/figures/' \
         'state/' 'corpus/' 'events/' 'docs/reports/' 'docs/data/' 'docs/index.html' \
         'framework/' 'controls.yaml' 'dixie_evidence.yaml' 'seldon.yaml' 'CLAUDE.md'; do
  moved=$(changed_and_new "$p")
  if [ -n "$moved" ]; then
    echo "FAIL protected path moved: $p"; echo "$moved" | sed 's/^/       /'; fail=1
  fi
done

# 2. No task file or earlier RESULT modified (untracked task files are the Desktop's, and
#    `check_protected_lib.sh` already drops them from the listing).
moved=$(git diff --name-only HEAD -- 'cc_tasks/')
if [ -n "$moved" ]; then
  echo "FAIL a tracked cc_tasks/ file changed:"; echo "$moved" | sed 's/^/       /'; fail=1
fi

# 3. Every path that moved is on the list.
ALLOWED=(
  'assessment/harness/scan/run.py' 'assessment/harness/scan/publish.py'
  'assessment/harness/scan/rederive.py' 'assessment/harness/scan/spot.py'
  'scripts/build_l0_matrices.py' 'scripts/score.py' 'scripts/prescriptions.py'
  'scripts/build_l0_report.py' 'scripts/build_l0_site.py' 'scripts/render_spot_scan.py'
  'scripts/check_protected_spot.sh'
  'mcp/airkg_tools.py' 'docs/design/mcp_over_the_graph.md'
  'cc_tasks/templates/spot_scan.md' 'cc_tasks/2026-09-19_spot_scan_RESULT.md'
  'tests/test_spot_scan.py'
)
while IFS= read -r path; do
  [ -z "$path" ] && continue
  ok=0
  for a in "${ALLOWED[@]}"; do [ "$path" = "$a" ] && ok=1 && break; done
  if [ "$ok" = 0 ]; then echo "FAIL not in the write set: $path"; fail=1; fi
done < <({ git diff --name-only HEAD; git ls-files --others --exclude-standard; } | sort -u)

# 4. The throwaway run left nothing behind: no spot payload, no spot shard, no spot matrix, no
#    staging directory for one.
left=$(ls state/spot_* events/cycle-spot_* docs/reports/scan_matrix_*spot_* 2>/dev/null;
       ls -d state/evidence_staging/spot_* 2>/dev/null)
if [ -n "$left" ]; then
  echo "FAIL the loopback spot run left files in the tree:"; echo "$left" | sed 's/^/       /'
  fail=1
fi

if [ "$fail" = 0 ]; then echo "PROTECTED PATHS OK"; fi
exit "$fail"
