#!/usr/bin/env bash
. "$(dirname "$0")/check_protected_lib.sh"
# The write set of `cc_tasks/2026-09-18_manners_status_and_b5_control.md`, asserted against HEAD.
#
#   "`state/`, `corpus/`, `docs/reports/` byte-identical", and the write set the task file lists.
#
# The task file's write set was too narrow in the places its RESULT §3 names, each asserted here:
#
#   * `CONTROL_LEGS` is in `run.py`, not `rules/__init__.py`, and decision 3 needed
#     `run.run_controls` to scan a fixture's products and judge the body legs over them; the
#     payload's `robots_log` (decision 1's manners log line) is written there too.
#   * `rules/__init__.py` moved for `body_groups` (a two-product control fixture IS a body) and
#     for generation 13, not for `CONTROL_LEGS`.
#   * Decision 4's contradiction is in the COLLECTOR (`dcat.fetch_catalog` computes membership;
#     no rule can, rules are pure), so `collectors/dcat.py` and `collectors/v2clauses.py`
#     moved, and the new rule is `RULE-D4-v3` because `RULE-D4-v2` already exists.
#   * The record moved in three `framework_writeback` events: the rule ids, the prescription
#     layer's `verifies_by`, and the D4 indicator's `tier_source` (three derived writers).
#   * `scripts/exercise_dcat_field_rules.py`: its pinned, unpublished distribution moved with the
#     membership test, and it now reports the per-surface membership move.
#   * Four derived views of the record and the harness, regenerated by their own generators:
#     `docs/data/ai_readiness_framework.json` + `docs/data/index.json`
#     (`build_l0_site.py --only sources_per_check --only framework_copy --only data_manifest`),
#     `docs/design/scan_tool_map.md` (`scan_tool_map.py`), `docs/design/mcp_over_the_graph.md`
#     (`mcp/airkg_doc.py`).
#   * Two test literals the change moves: `test_scan_harness.py` (control Finding count, now
#     derived per product) and `test_rule_a12_v3.py` (the `unobserved_error` callers).
#   * `corpus/` moved on ONE file, appended to: `corpus/quarantine/evidence_scan_fixture/
#     reason.txt`, the record `scripts/quarantine_fixture_evidence.py --clear-redirects` writes
#     when it clears the evidence-guard redirect log (DD-063 decision 3). The litter was this
#     session's own — a module-scoped control fixture in `tests/test_b5_control.py` set up
#     before conftest's redirect, fixed here, and exploratory control runs from stdin.
set -u
cd "$(dirname "$0")/.." || exit 2
fail=0
PY=/opt/anaconda3/bin/python3

changed_and_new() {
  { git diff --name-only HEAD -- "$@"; git ls-files --others --exclude-standard -- "$@"; } \
    | sed '/^$/d' | sort -u
}

# 1. Untouched outright.
SWEEP_RECORD='corpus/quarantine/evidence_scan_fixture/reason.txt'
for p in 'state/' 'corpus/' 'docs/reports/' 'docs/research/' 'kg/' 'LICENSE' 'LICENSE-DATA' \
         'controls.yaml' 'seldon.yaml' 'CLAUDE.md' 'assessment/cq/'; do
  moved=$(changed_and_new "$p" | grep -vxF "$SWEEP_RECORD")
  if [ -n "$moved" ]; then
    echo "FAIL protected path moved: $p"; echo "$moved" | sed 's/^/       /'; fail=1
  fi
done

# 2. Every path that moved is on the list.
ALLOWED=(
  'assessment/harness/scan/manners.py'
  'assessment/harness/scan/run.py'
  'assessment/harness/scan/params.yaml'
  'assessment/harness/scan/rules/__init__.py'
  'assessment/harness/scan/rules/rule_d4_v3.py'
  'assessment/harness/scan/collectors/dcat.py'
  'assessment/harness/scan/collectors/v2clauses.py'
  'assessment/harness/scan/fixtures/server.py'
  'assessment/harness/scan/fixtures/body_two_products/MANIFEST.json'
  'assessment/harness/scan/fixtures/body_two_products/second.html'
  'assessment/harness/scan/fixtures/body_two_products/data.json'
  'assessment/harness/scan/fixtures/body_two_products/sitemap.xml'
  'assessment/harness/scan/fixtures/body_two_products_split/MANIFEST.json'
  'assessment/harness/scan/fixtures/body_two_products_split/second.html'
  'framework/ai_readiness_framework.json'
  'events/batch-033_framework.jsonl'
  'scripts/exercise_dcat_field_rules.py'
  'scripts/check_protected_manners.sh'
  'tests/test_manners_robots_status.py'
  'tests/test_b5_control.py'
  'tests/test_d4_membership.py'
  'tests/test_dcat_field_rules.py'
  'tests/test_schema_field_rules.py'
  'tests/test_scan_harness.py'
  'tests/test_rule_a12_v3.py'
  'docs/data/ai_readiness_framework.json'
  'docs/data/index.json'
  'docs/design/scan_tool_map.md'
  'docs/design/mcp_over_the_graph.md'
  'corpus/quarantine/evidence_scan_fixture/reason.txt'
  'seldon_events.jsonl'
  'cc_tasks/2026-09-18_manners_status_and_b5_control_RESULT.md'
)
while read -r f; do
  [ -z "$f" ] && continue
  ok=0
  for a in "${ALLOWED[@]}"; do [ "$f" = "$a" ] && ok=1; done
  if [ "$ok" -eq 0 ]; then echo "FAIL moved outside the write set: $f"; fail=1; fi
done <<< "$(changed_and_new .)"

# 3. No shipped rule module moved: the only rule file that changed is the new one.
x=$(git diff --name-only HEAD -- 'assessment/harness/scan/rules/rule_*.py')
[ -n "$x" ] && { echo "FAIL a shipped rule module moved:"; echo "$x"; fail=1; }

# 4. The record: only the derived rule-id, prescription and tier cells for D4, and E5's fixture
#    pin. Every other node, every other edge and `counts` is HEAD's.
git show HEAD:framework/ai_readiness_framework.json > /tmp/airkg_fw_head_m.json
if ! $PY - <<'EOF'
import json, sys
a = json.load(open("/tmp/airkg_fw_head_m.json"))
b = json.load(open("framework/ai_readiness_framework.json"))
bad = []
if {k: v for k, v in a.items() if k not in ("nodes", "edges")} != \
        {k: v for k, v in b.items() if k not in ("nodes", "edges")}:
    bad.append("something outside `nodes`/`edges` moved (counts included)")
an, bn = {n["id"]: n for n in a["nodes"]}, {n["id"]: n for n in b["nodes"]}
if set(an) != set(bn):
    bad.append(f"the node set moved: +{sorted(set(bn) - set(an))} -{sorted(set(an) - set(bn))}")
ALLOWED = {"spec:D4": {"rule_id"}, "spec:E5": {"collector_pin"}, "ind:D4": {"tier_source"}}
moved_nodes = {}
for i in an:
    x, y = an[i], bn.get(i, {})
    if x.get("labels") != y.get("labels"):
        bad.append(f"{i}: labels moved")
    px, py = x["properties"], y.get("properties", {})
    moved = {k for k in set(px) | set(py) if px.get(k) != py.get(k)}
    if moved:
        moved_nodes[i] = moved
for i, moved in moved_nodes.items():
    p = bn[i]["properties"]
    if i in ALLOWED:
        if moved != ALLOWED[i]:
            bad.append(f"{i}: moved {sorted(moved)}, allowed {sorted(ALLOWED[i])}")
    elif "Action" in bn[i]["labels"] and p.get("leg") == "D4":
        if moved != {"verifies_by"} or p["verifies_by"] != "RULE-D4-v3":
            bad.append(f"{i}: a D4 action moved {sorted(moved)}")
    else:
        bad.append(f"{i}: moved {sorted(moved)} and is not in the write set")
if bn["spec:D4"]["properties"]["rule_id"] != "RULE-D4-v3":
    bad.append("spec:D4 does not name RULE-D4-v3")
pin = bn["spec:E5"]["properties"]["collector_pin"]
if "body_two_products," not in pin or "body_two_products_split" not in pin:
    bad.append("spec:E5's fixture pin does not name the two body fixtures")
key = lambda e: (e["from"], e["type"], e["to"], e.get("properties", {}).get("outcome"))
ae, be = {key(e): e for e in a["edges"]}, {key(e): e for e in b["edges"]}
if set(ae) != set(be):
    bad.append("the edge set moved")
for k in ae:
    if ae[k] != be.get(k):
        props = be[k].get("properties", {})
        diff = {p for p in set(ae[k].get("properties", {})) | set(props)
                if ae[k].get("properties", {}).get(p) != props.get(p)}
        if not (k[1] == "REMEDIATES" and props.get("leg") == "D4" and diff == {"rule_id"}
                and props["rule_id"] == "RULE-D4-v3"):
            bad.append(f"edge {k} moved {sorted(diff)}")
print("\n".join(f"FAIL {m}" for m in bad)
      or f"   record: {len(moved_nodes)} node(s) moved, all derived D4/E5 cells")
sys.exit(1 if bad else 0)
EOF
then fail=1; fi

# 5. params.yaml moved in exactly two places: two new control tables and D4's two membership keys.
git show HEAD:assessment/harness/scan/params.yaml > /tmp/airkg_params_head_m.yaml
if ! $PY - <<'EOF'
import sys, yaml
a = yaml.safe_load(open("/tmp/airkg_params_head_m.yaml"))
b = yaml.safe_load(open("assessment/harness/scan/params.yaml"))
bad = []
ea, eb = a["e5_control"]["expected_verdicts"], b["e5_control"]["expected_verdicts"]
if {k: v for k, v in eb.items() if k in ea} != ea:
    bad.append("an existing control table moved")
if set(eb) - set(ea) != {"body_two_products", "body_two_products_split"}:
    bad.append(f"control tables added: {sorted(set(eb) - set(ea))}")
if set(b["d4_catalog"]) - set(a["d4_catalog"]) != {"membership_fields", "default_ports"}:
    bad.append("d4_catalog gained something other than membership_fields and default_ports")
if {k: v for k, v in b["d4_catalog"].items() if k in a["d4_catalog"]} != a["d4_catalog"]:
    bad.append("an existing d4_catalog key moved")
for k in ("e5_control", "d4_catalog"):
    a.pop(k); b.pop(k)
if a != b:
    bad.append(f"params moved outside e5_control and d4_catalog: "
               f"{sorted(k for k in set(a) | set(b) if a.get(k) != b.get(k))}")
print("\n".join(f"FAIL {m}" for m in bad) or "   params: two control tables, two D4 keys")
sys.exit(1 if bad else 0)
EOF
then fail=1; fi

# 6. Logs are append-only; the framework shard gained exactly the three write-back events.
for f in events/ seldon_events.jsonl; do
  if git diff HEAD -- "$f" | grep -q '^-[^-]'; then
    echo "FAIL $f lost or changed a line; the log is append-only"; fail=1
  fi
done
added=$(git diff HEAD -U0 -- events/batch-033_framework.jsonl | grep -cE '^\+[^+]')
[ "$added" != "3" ] && { echo "FAIL the framework shard gained $added line(s), not 3"; fail=1; }

# 7a. The sweep record only GREW, by one clearance naming this task.
if git diff HEAD -- "$SWEEP_RECORD" | grep -q '^-[^-]'; then
  echo "FAIL $SWEEP_RECORD lost or changed a line"; fail=1
fi
if [ -n "$(git diff --name-only HEAD -- "$SWEEP_RECORD")" ]; then
  n=$(git diff HEAD -U0 -- "$SWEEP_RECORD" | grep -c 'evidence-guard redirect log cleared')
  [ "$n" != "1" ] && { echo "FAIL $SWEEP_RECORD gained $n clearance(s), not 1"; fail=1; }
  git diff HEAD -- "$SWEEP_RECORD" | grep -q '^+.*2026-09-18_manners_status_and_b5_control' \
    || { echo "FAIL the clearance does not name this task"; fail=1; }
fi

# 7b. The site's copy is the record, byte for byte; the derived pages are their generators'.
cmp -s framework/ai_readiness_framework.json docs/data/ai_readiness_framework.json \
  || { echo "FAIL docs/data/ai_readiness_framework.json is not the record"; fail=1; }
$PY scripts/scan_tool_map.py --check >/dev/null \
  || { echo "FAIL docs/design/scan_tool_map.md is not its generator's output"; fail=1; }
$PY mcp/airkg_doc.py --check >/dev/null \
  || { echo "FAIL docs/design/mcp_over_the_graph.md is not what the tools answer"; fail=1; }
x=$(git diff HEAD -U0 -- docs/data/index.json | grep -E '^[+-][^+-]' \
    | grep -vE '^[+-] *"(sha256|bytes|built_at|build_commit)": ')
[ -n "$x" ] && { echo "FAIL index.json moved outside digests and the build stamp:"; \
                 echo "$x" | cut -c1-160; fail=1; }

# 7. Every `passes_all` file the body fixtures do not overlay is inherited, not copied.
for f in index.html robots.txt llms.txt openapi.json methodology.html; do
  for d in body_two_products body_two_products_split; do
    [ -e "assessment/harness/scan/fixtures/$d/$f" ] \
      && { echo "FAIL $d copies passes_all/$f instead of inheriting it"; fail=1; }
  done
done

if [ "$fail" -eq 0 ]; then echo "PROTECTED PATHS OK"; fi
exit "$fail"
