#!/usr/bin/env bash
. "$(dirname "$0")/check_protected_lib.sh"
# The write set of `cc_tasks/2026-10-07_parallel_hosts_and_fast_gate.md`, asserted against the
# commit the task started from (default 6ed1bd77, HEAD when it was launched), so it reads the
# same before and after the task's own commit.
#
# The task's write set: `manners.py`, `run.py`, `params.yaml` (`manners.max_parallel_hosts`
# only), the new guards, `tests/conftest.py`, `pyproject.toml` (dev dependencies only),
# `Makefile`, `CLAUDE.md` (two sections), `scripts/jobs/` (the daily job and its plist), the
# RESULT. Widened, each for the reason the RESULT gives:
#
#   * `clock.py`: `VirtualClock` takes a lock; `+=` from two workers could move time backwards.
#   * `model.py`: `UNHASHED_NESTED_KEYS` (the new key shapes no recorded byte, so it may not move
#     `params_hash`), and `store_evidence` renames into place (two workers, one body).
#   * `scripts/measure_parallel_hosts.py`: decision 4's measurement, so the number has a script.
#   * `docs/brief/E_architecture.md`, `docs/evidence/claims.yaml`: derived views that cite source
#     LINE numbers in the files above, regenerated by their own generators.
#
# Byte-identical: every rule, collector, `runner.py`, `scripts/score.py`, every stored payload,
# the framework record, the event log and every task file.
set -u
cd "$(dirname "$0")/.." || exit 2
BASE="${1:-6ed1bd77}"
PY="${PY:-/opt/anaconda3/bin/python3}"
fail=0

changed_and_new() {
  { git diff --name-only "$BASE" -- "$@"; git ls-files --others --exclude-standard -- "$@"; } \
    | sed '/^$/d' | sort -u
}

allowed() {
  case "$1" in
    assessment/harness/scan/manners.py|assessment/harness/scan/run.py) return 0 ;;
    assessment/harness/scan/params.yaml|assessment/harness/scan/clock.py) return 0 ;;
    assessment/harness/scan/model.py) return 0 ;;
    tests/test_parallel_hosts.py|tests/test_daily_suite_job.py|tests/conftest.py) return 0 ;;
    pyproject.toml|Makefile|CLAUDE.md|seldon_events.jsonl) return 0 ;;
    scripts/jobs/airkg_daily_suite.sh|scripts/jobs/com.brock.airkg-daily-suite.plist) return 0 ;;
    scripts/measure_parallel_hosts.py|scripts/check_protected_parallel_hosts.sh) return 0 ;;
    docs/brief/E_architecture.md|docs/evidence/claims.yaml) return 0 ;;
    cc_tasks/2026-10-07_parallel_hosts_and_fast_gate_RESULT.md) return 0 ;;
  esac
  return 1
}

while IFS= read -r path; do
  [ -z "$path" ] && continue
  allowed "$path" || { echo "FAIL path outside the write set moved: $path"; fail=1; }
done < <(changed_and_new .)

for p in assessment/harness/scan/rules assessment/harness/scan/collectors \
         assessment/harness/scan/runner.py scripts/score.py state events \
         framework/ai_readiness_framework.json corpus/manifest.json docs/reports; do
  if [ -n "$(changed_and_new "$p")" ]; then echo "FAIL $p must be byte-identical and moved"; fail=1; fi
done

# Every task file other than this task's RESULT: immutable once written.
moved_tasks=$(git diff --name-only "$BASE" -- cc_tasks/ \
  | grep -vxF 'cc_tasks/2026-10-07_parallel_hosts_and_fast_gate_RESULT.md' || true)
if [ -n "$moved_tasks" ]; then echo "FAIL a task file moved: $moved_tasks"; fail=1; fi

# Append-only: the Seldon store.
removed=$(git diff "$BASE" -- seldon_events.jsonl | grep -c '^-[^-]' || true)
if [ "$removed" -ne 0 ]; then echo "FAIL seldon_events.jsonl lost or changed $removed line(s)"; fail=1; fi

# params.yaml: `manners.max_parallel_hosts` and nothing else; pyproject.toml: the dev extra and
# nothing else; CLAUDE.md: the two named sections and nothing else.
"$PY" - "$BASE" <<'EOF' || fail=1
import re, subprocess, sys, tomllib, yaml
base = sys.argv[1]
def at(rel):
    return subprocess.run(["git", "show", f"{base}:{rel}"], capture_output=True, text=True,
                          check=True).stdout
bad = 0
then = yaml.safe_load(at("assessment/harness/scan/params.yaml"))
now = yaml.safe_load(open("assessment/harness/scan/params.yaml", encoding="utf-8"))
now["manners"].pop("max_parallel_hosts", None)
if then != now:
    print("FAIL params.yaml moved beyond manners.max_parallel_hosts"); bad = 1
t0, t1 = tomllib.loads(at("pyproject.toml")), tomllib.load(open("pyproject.toml", "rb"))
d0, d1 = t0["project"]["optional-dependencies"].pop("dev"), t1["project"]["optional-dependencies"].pop("dev")
if t0 != t1 or set(d1) - set(d0) != {"pytest-xdist==3.8.0"} or set(d0) - set(d1):
    print("FAIL pyproject.toml moved beyond the dev extra's pytest-xdist"); bad = 1
def sections(text):
    parts = re.split(r"(?m)^(?=#{2,3} )", text)
    return {p.splitlines()[0]: p for p in parts if p.strip()}
s0, s1 = sections(at("CLAUDE.md")), sections(open("CLAUDE.md", encoding="utf-8").read())
mine = {"### The RESULT waits for the suite (operator-ordered, 2026-09-09)",
        "### Suite tiers (operator-ordered, 2026-09-09)"}
if set(s0) != set(s1):
    print("FAIL CLAUDE.md headings moved"); bad = 1
moved = sorted(h for h in s0 if h in s1 and s0[h] != s1[h])
if set(moved) - mine:
    print(f"FAIL CLAUDE.md sections outside the two named moved: {sorted(set(moved) - mine)}"); bad = 1
sys.exit(bad)
EOF

# The regenerated views are their generators' output exactly.
"$PY" scripts/build_evidence_map.py --check >/dev/null 2>&1 \
  || { echo "FAIL docs/evidence/claims.yaml drifts from its generator"; fail=1; }
"$PY" scripts/build_brief_pack.py --check >/dev/null 2>&1 \
  || { echo "FAIL docs/brief drifts from its generator"; fail=1; }
"$PY" scripts/build_adopt_requirements.py --check >/dev/null 2>&1 \
  || { echo "FAIL docs/adopt/run_on_your_site.md drifts from pyproject.toml"; fail=1; }

if [ "$fail" -eq 0 ]; then echo "PROTECTED PATHS: PASS"; else echo "PROTECTED PATHS: FAIL"; fi
exit "$fail"
