#!/usr/bin/env bash
. "$(dirname "$0")/check_protected_lib.sh"
# The write set of `cc_tasks/2026-09-18_tool_docs_ingest.md`, asserted against HEAD.
#
#   "`state/`, `docs/reports/` byte-identical", and the write set the task file lists.
#
# Six paths moved that the task file's write set does not name, and the RESULT reports each:
#
#   * scripts/build_l0_site.py — no `--only` flag wrote `docs/data/corpus_manifest.json`, so the
#     narrow build recorded the new corpus manifest's digest in index.json over a copy still
#     holding the old one, and `tests/test_publication.py` failed on it. One `_ONLY` key,
#     `corpus_copy`, inserted; nothing removed.
#   * docs/data/corpus_manifest.json — that copy.
#   * CITATION.cff, .zenodo.json and their docs/data/ twins — the data manifest's build date
#     travels in their text (`_ONLY["data_manifest"]`), and the build ran on a new UTC day.
#   * tests/test_mcp_server.py and docs/design/mcp_over_the_graph.md — the MCP server's
#     `get_overview` reports the tier distribution, and both its test literal and its page
#     (generated by running the tools, `mcp/airkg_doc.py`) hold it. The first full-suite run
#     failed on exactly these two; they are views of the tiers like the tool map.
set -u
cd "$(dirname "$0")/.." || exit 2
fail=0
PY=/opt/anaconda3/bin/python3

changed_and_new() {
  { git diff --name-only HEAD -- "$@"; git ls-files --others --exclude-standard -- "$@"; } \
    | sed '/^$/d' | sort -u
}

# 1. Untouched outright.
for p in 'state/' 'docs/reports/' 'docs/research/' 'kg/' 'assessment/' 'LICENSE' \
         'LICENSE-DATA' 'controls.yaml' 'seldon.yaml' 'docs/data/sources_per_check.json' \
         'docs/data/results_tagged.json'; do
  moved=$(changed_and_new "$p")
  if [ -n "$moved" ]; then
    echo "FAIL protected path moved: $p"; echo "$moved" | sed 's/^/       /'; fail=1
  fi
done

# 2. Every path that moved is on the list.
ALLOWED=(
  'corpus/tools/oasdiff/README.md'
  'corpus/tools/wayback-cdx-server/README.md'
  'corpus/evidence/decisions.jsonl'
  'corpus/manifest.json'
  'dixie_evidence.yaml'
  'scripts/admit_tool_docs.py'
  'scripts/tag_measurement_tiers.py'
  'scripts/build_l0_site.py'
  'scripts/check_protected_tool_docs.sh'
  'framework/ai_readiness_framework.json'
  'events/batch-033_framework.jsonl'
  'tests/test_measurement_tiers.py'
  'tests/test_mcp_server.py'
  'docs/design/mcp_over_the_graph.md'
  'docs/design/scan_tool_map.md'
  'docs/data/ai_readiness_framework.json'
  'docs/data/corpus_manifest.json'
  'docs/data/index.json'
  'docs/data/CITATION.cff'
  'docs/data/zenodo.json'
  'CITATION.cff'
  '.zenodo.json'
  'seldon_events.jsonl'
  'cc_tasks/2026-09-18_tool_docs_ingest_RESULT.md'
)
while read -r f; do
  [ -z "$f" ] && continue
  ok=0
  for a in "${ALLOWED[@]}"; do [ "$f" = "$a" ] && ok=1; done
  if [ "$ok" -eq 0 ]; then echo "FAIL moved outside the write set: $f"; fail=1; fi
done <<< "$(changed_and_new .)"

# 3. The record: only the tier properties, only on A7, F2 and F3, each now O / open_tool with
#    no shopping-list entry. Every other node, every edge and `counts` is HEAD's.
git show HEAD:framework/ai_readiness_framework.json > /tmp/airkg_fw_head_t.json
if ! $PY - <<'EOF'
import json, sys
a = json.load(open("/tmp/airkg_fw_head_t.json"))
b = json.load(open("framework/ai_readiness_framework.json"))
OK = {"measurement_tier", "measurement_basis", "tier_source", "tier_rule", "tier_note",
      "tier_field", "tier_collector", "tier_unassigned_reason", "open_tool_candidate"}
THE_3 = {"A7", "F2", "F3"}
bad = []
if {k: v for k, v in a.items() if k != "nodes"} != {k: v for k, v in b.items() if k != "nodes"}:
    bad.append("something outside `nodes` moved")
an, bn = {n["id"]: n for n in a["nodes"]}, {n["id"]: n for n in b["nodes"]}
if set(an) != set(bn):
    bad.append("the node set moved")
touched = set()
for i in an:
    x, y = an[i], bn.get(i, {})
    if x.get("labels") != y.get("labels"):
        bad.append(f"{i}: labels moved")
    px, py = x["properties"], y.get("properties", {})
    moved = {k for k in set(px) | set(py) if px.get(k) != py.get(k)}
    if not moved:
        continue
    if "AssessmentIndicator" not in x["labels"]:
        bad.append(f"{i}: a non-indicator node moved {sorted(moved)}")
        continue
    touched.add(px["code"])
    if moved - OK:
        bad.append(f"{i}: moved outside the tier keys {sorted(moved - OK)}")
if touched != THE_3:
    bad.append(f"the rows that moved are not A7, F2, F3: {sorted(touched)}")
for c in THE_3:
    p = bn[f"ind:{c}"]["properties"]
    if (p.get("measurement_tier"), p.get("measurement_basis")) != ("O", "open_tool"):
        bad.append(f"{c}: not O / open_tool")
    if p.get("open_tool_candidate") or p.get("tier_unassigned_reason"):
        bad.append(f"{c}: tiered and still carries a candidate or a reason")
    if "corpus/tools/" not in p.get("tier_source", ""):
        bad.append(f"{c}: the tier source does not cite the admitted document")
print("\n".join(f"FAIL {m}" for m in bad)
      or "   record: only tier keys, only on A7, F2, F3")
sys.exit(1 if bad else 0)
EOF
then fail=1; fi

# 4. The corpus manifest gained the two documents; the only existing entry that moved is the
#    NAO 216-128 OCR sidecar the sweep re-observed (its committed bytes differ from the ones
#    swept on 2026-09-10; the RESULT reports it).
git show HEAD:corpus/manifest.json > /tmp/airkg_manifest_head_t.json
if ! $PY - <<'EOF'
import json, sys
a = json.load(open("/tmp/airkg_manifest_head_t.json"))["entries"]
b = json.load(open("corpus/manifest.json"))["entries"]
bad = []
if set(b) - set(a) != {"oasdiff-readme", "wayback-cdx-server-api-readme"} or set(a) - set(b):
    bad.append(f"entries added {sorted(set(b) - set(a))}, removed {sorted(set(a) - set(b))}")
moved = sorted(k for k in a if k in b and a[k] != b[k])
if moved not in ([], ["nao-216-128-artificial-intelligence-in-noaa"]):
    bad.append(f"existing entries moved: {moved}")
for k in ("oasdiff-readme", "wayback-cdx-server-api-readme"):
    e = b.get(k) or {}
    if (e.get("screening", {}).get("decision"), e.get("integrity", {}).get("status")) != (
            "included", "verified"):
        bad.append(f"{k}: not included + verified")
print("\n".join(f"FAIL {m}" for m in bad) or "   manifest: +2 entries, included and verified")
sys.exit(1 if bad else 0)
EOF
then fail=1; fi

# 5. The dixie config moved on the document_dirs line alone.
x=$(git diff HEAD -U0 -- dixie_evidence.yaml | grep -E '^[+-][^+-]' | grep -vE '^[+-]document_dirs: ')
[ -n "$x" ] && { echo "FAIL dixie_evidence.yaml moved outside document_dirs:"; echo "$x"; fail=1; }

# 6. The site's copies are their records, byte for byte.
cmp -s framework/ai_readiness_framework.json docs/data/ai_readiness_framework.json \
  || { echo "FAIL docs/data/ai_readiness_framework.json is not the record"; fail=1; }
cmp -s corpus/manifest.json docs/data/corpus_manifest.json \
  || { echo "FAIL docs/data/corpus_manifest.json is not the corpus manifest"; fail=1; }

# 7. The data manifest moved on digests and the build stamp alone.
x=$(git diff HEAD -U0 -- docs/data/index.json | grep -E '^[+-][^+-]' \
    | grep -vE '^[+-] *"(sha256|bytes|built_at|build_commit)": ')
[ -n "$x" ] && { echo "FAIL index.json moved outside digests and the build stamp:"; \
                 echo "$x" | cut -c1-160; fail=1; }

# 8. The tool map is its generator's output.
$PY scripts/scan_tool_map.py --check >/dev/null \
  || { echo "FAIL docs/design/scan_tool_map.md is not its generator's output"; fail=1; }

# 8b. The MCP page is what the tools answer now.
$PY mcp/airkg_doc.py --check >/dev/null \
  || { echo "FAIL docs/design/mcp_over_the_graph.md is not what the tools answer"; fail=1; }

# 9. The site builder change is a pure insertion of the `corpus_copy` key.
x=$(git diff HEAD -U0 -- scripts/build_l0_site.py | grep -cE '^-[^-]')
[ "$x" != "0" ] && { echo "FAIL scripts/build_l0_site.py removed $x line(s)"; fail=1; }
git diff HEAD -U0 -- scripts/build_l0_site.py | grep -qE '^\+.*"corpus_copy"' \
  || { echo "FAIL the builder change is not the corpus_copy key"; fail=1; }

# 10. Logs are append-only: one write-back event on the framework shard; the dixie ledger
#     gains 2 imports, 3 observations, 3 integrity checks and 1 epoch.
for f in events/ seldon_events.jsonl corpus/evidence/decisions.jsonl; do
  if git diff HEAD -- "$f" | grep -q '^-[^-]'; then
    echo "FAIL $f lost or changed a line; the log is append-only"; fail=1
  fi
done
added=$(git diff HEAD -U0 -- events/batch-033_framework.jsonl | grep -cE '^\+[^+]')
[ "$added" != "1" ] && { echo "FAIL the framework shard gained $added line(s), not 1"; fail=1; }
added=$(git diff HEAD -U0 -- corpus/evidence/decisions.jsonl | grep -cE '^\+[^+]')
[ "$added" != "9" ] && { echo "FAIL the dixie ledger gained $added line(s), not 9"; fail=1; }

if [ "$fail" -eq 0 ]; then echo "PROTECTED PATHS OK"; fi
exit "$fail"
