#!/usr/bin/env bash
# The zero-edits list of `cc_tasks/2026-09-13_ephemeral_provenance.md`, asserted against HEAD:
#
#   "Zero edits to: rule modules, harness, payloads, prior Results' values and states, prior
#    RESULTs, figures, section prose, the skeleton, the record, corpus/, docs/ beyond
#    data/results_tagged.json"
#
# widened by ADDENDUM_1's gate, FOR THAT ADDENDUM ONLY, to `docs/index.html`,
# `docs/data/index.json` and the two citation copies. `docs/reports/publication.yaml` is the
# declaration A4 requires the licences to be declared in, so it is editable by the same clause.
#
# Three entries are not path lists and are checked as themselves:
#
#   * THE MATRICES AND REPORT FRAGMENTS are regenerated by this task's re-derivation gate
#     (`scripts/rederive_tagged_results.py` drives `build_l0_matrices` over the snapshot cycle
#     for real, into the shipped paths). Protected here, so "the generator reproduces its own
#     output byte-for-byte" is asserted rather than asserted-about.
#   * `state/` may not be MODIFIED, and may gain only the files in NEW_STATE. The file this
#     whole task is about — `state/scan_matrix_2026-09-10.json` — must NEVER appear there: its
#     absence is the decision the registry now records (`materialized: false`), and the
#     re-derivation drives its generator with `OUT_DIR` pointed at a temporary tree so the side
#     effect is not produced. Its Tier C sibling,
#     `state/scan_matrix_tierc_2026-09-10.json`, is the same thing and is likewise absent — the
#     previous gate deleted that one by hand after each run, which is precisely the special case
#     decision 4 replaced.
#   * `events/` is untouched whole: this task writes to the SELDON log (`seldon_events.jsonl`),
#     which is append-only and is checked for deletions instead.
set -u
cd "$(dirname "$0")/.." || exit 2
fail=0

# Byte-identical, and no new file inside them either.
protected=(
  'assessment/'
  'corpus/'
  'events/'
  'framework/'
  'docs/reports/sections/'
  'docs/reports/generated/'
  'docs/crosswalk/usafacts_operationalization_skeleton.md'
  'docs/robots.txt'
  'docs/llms.txt'
  'docs/sitemap.xml'
  'docs/progress/'
)
for p in "${protected[@]}"; do
  changed=$(git diff --name-only HEAD -- "$p"; git ls-files --others --exclude-standard -- "$p")
  if [ -n "$changed" ]; then
    echo "FAIL protected path moved: $p"
    echo "$changed" | sed 's/^/       /'
    fail=1
  fi
done

# docs/ may change ONLY where the task and its addendum say it may.
DOCS_ALLOWED=(
  'docs/data/results_tagged.json'
  'docs/data/index.json'
  'docs/data/CITATION.cff'
  'docs/data/zenodo.json'
  'docs/index.html'
  'docs/reports/publication.yaml'
)
while read -r f; do
  [ -z "$f" ] && continue
  ok=0
  for allowed in "${DOCS_ALLOWED[@]}"; do [ "$f" = "$allowed" ] && ok=1; done
  if [ "$ok" -eq 0 ]; then
    echo "FAIL docs/ changed outside the zero-edits widening: $f"; fail=1
  fi
done <<< "$(git diff --name-only HEAD -- 'docs/'; git ls-files --others --exclude-standard -- 'docs/')"

# The published matrices of the snapshot cycle: regenerated this session, and identical.
mx=$(git diff --name-only HEAD -- 'docs/reports/scan_matrix_*')
if [ -n "$mx" ]; then
  echo "FAIL a published matrix changed; the generator does not reproduce its own output:"
  echo "$mx" | sed 's/^/       /'; fail=1
fi

# The report as built: this task rebuilds no report and touches no prose.
rep=$(git diff --name-only HEAD -- 'docs/reports/2026-09_fss_ai_readiness_L0.md' \
                                   'docs/reports/2026-09_fss_ai_readiness_L0.pdf')
if [ -n "$rep" ]; then
  echo "FAIL the built report changed; this task edits no prose and rebuilds no report:"
  echo "$rep" | sed 's/^/       /'; fail=1
fi

# Prior RESULTs are execution records and are never edited.
prior=$(git diff --name-only HEAD -- 'cc_tasks/*_RESULT.md')
if [ -n "$prior" ]; then
  echo "FAIL a prior RESULT changed:"; echo "$prior" | sed 's/^/       /'; fail=1
fi

# state/: no modification, and only the declared additions.
NEW_STATE=(
  'state/rederive_tagged_2026-09-13.json'
  'state/ephemeral_provenance_2026-09-13.json'
)
mod=$(git diff --name-only HEAD -- 'state/')
if [ -n "$mod" ]; then
  echo "FAIL a stored payload was MODIFIED:"; echo "$mod" | sed 's/^/       /'; fail=1
fi
while read -r f; do
  [ -z "$f" ] && continue
  ok=0
  for allowed in "${NEW_STATE[@]}"; do [ "$f" = "$allowed" ] && ok=1; done
  if [ "$ok" -eq 0 ]; then
    echo "FAIL an undeclared file appeared under state/: $f"; fail=1
  fi
done <<< "$(git ls-files --others --exclude-standard -- 'state/')"

# The two paths whose ABSENCE is the decision of record.
for ghost in 'state/scan_matrix_2026-09-10.json' 'state/scan_matrix_tierc_2026-09-10.json'; do
  if [ -e "$ghost" ]; then
    echo "FAIL $ghost EXISTS. Its absence is a recorded decision (the registry marks the"
    echo "     DataFile materialized: false) and the re-derivation drives its generator with"
    echo "     OUT_DIR pointed at a temporary tree. A file here means the redirect leaked."
    fail=1
  fi
done

# The Seldon event log is append-only: this task writes an artifact_updated and a link_created.
if git diff seldon_events.jsonl | grep -q '^-[^-]'; then
  echo "FAIL seldon_events.jsonl lost a line; the log is append-only"; fail=1
fi

if [ "$fail" -eq 0 ]; then
  echo "PASS  the harness, corpus/, events/, the record, the skeleton, section prose, the report"
  echo "      fragments, the built report, every published matrix, robots.txt, llms.txt and the"
  echo "      sitemap are byte-identical to HEAD; docs/ changed only where the addendum widened"
  echo "      it; state/ gained only the declared files, lost nothing, and holds neither matrix"
  echo "      whose absence is the decision of record; the Seldon log only grew"
fi

echo
echo "what DID change:"
{ git diff --name-only HEAD; git ls-files --others --exclude-standard; } | sort -u | sed 's/^/       /'
exit "$fail"
