#!/usr/bin/env bash
. "$(dirname "$0")/check_protected_lib.sh"
# The write set of `cc_tasks/2026-09-22_brief_deck_assembly.md`, asserted against the commit the
# task was launched on.
#
#   "**Write set:** `scripts/build_brief_deck.py`, `docs/deck/**` (all new),
#    `tests/test_brief_deck.py`, `scripts/build_brief_pack.py` (decision 7 only), `docs/brief/**`
#    (regenerated by decision 7 only), `tests/test_brief_pack.py` (decision 7's test),
#    `scripts/build_framework_deck.py` (import refactor only, output byte-identical), this task's
#    `scripts/check_protected_brief_deck.sh`, the RESULT. Byte-identical: `framework/`, `state/`,
#    `events/`, `docs/reports/`, `docs/data/`, `docs/crosswalk/`, `assessment/`, `corpus/`,
#    `mcp/`, `CITATION.cff`, `.zenodo.json`."
#
# Decision 7 was committed on its own (its gate, `check_protected_brief_pack.sh`, reads HEAD), so
# this check diffs against the launch commit rather than HEAD: BASE is the dispatcher's
# `dispatch_launched` record commit for this task (`92421acb`), the last commit before the task
# wrote anything. Override with BASE=<rev> to re-run it later.
set -u
cd "$(dirname "$0")/.." || exit 2
fail=0
PY=/opt/anaconda3/bin/python3
TASK_STEM=2026-09-22_brief_deck_assembly
BASE=${BASE:-a3756e3}

changed_and_new() {
  { git diff --name-only "$BASE" -- "$@"; git ls-files --others --exclude-standard -- "$@"; } \
    | sed '/^$/d' | sort -u
}

# 1. Untouched outright: the task's byte-identical list, plus every other store of record.
for p in 'framework/' 'state/' 'events/' 'docs/reports/' 'docs/data/' 'docs/crosswalk/' \
         'assessment/' 'corpus/' 'mcp/' 'CITATION.cff' '.zenodo.json' 'kg/' 'controls.yaml' \
         'dixie_evidence.yaml' 'seldon.yaml' 'Makefile' 'CLAUDE.md' 'LICENSE' 'LICENSE-DATA'; do
  moved=$(changed_and_new "$p")
  if [ -n "$moved" ]; then
    echo "FAIL protected path moved: $p"; echo "$moved" | sed 's/^/       /'; fail=1
  fi
done

# 2. Every path that moved is on the write set.
while read -r f; do
  [ -z "$f" ] && continue
  case "$f" in
    docs/deck/*|docs/brief/*|scripts/build_brief_deck.py|scripts/build_brief_pack.py|\
    scripts/build_framework_deck.py|tests/test_brief_deck.py|tests/test_brief_pack.py|\
    scripts/check_protected_brief_deck.sh|seldon_events.jsonl|\
    "cc_tasks/${TASK_STEM}_RESULT.md") ;;
    *) echo "FAIL moved outside the write set: $f"; fail=1 ;;
  esac
done <<< "$(changed_and_new .)"

# 3. docs/brief/ moved only in the two files decision 7 names and the ledger that holds its counts.
while read -r f; do
  [ -z "$f" ] && continue
  case "$f" in
    docs/brief/B_usafacts_delta.md|docs/brief/B_usafacts_delta.csv|docs/brief/numbers.json) ;;
    *) echo "FAIL docs/brief/ moved beyond decision 7: $f"; fail=1 ;;
  esac
done <<< "$(changed_and_new docs/brief/)"

# 4. A prior task file or RESULT is immutable.
if git diff --name-only "$BASE" -- cc_tasks/ | grep -v "^cc_tasks/${TASK_STEM}_RESULT.md$" | grep -q .; then
  echo "FAIL a tracked cc_tasks file changed:"; git diff --name-only "$BASE" -- cc_tasks/; fail=1
fi

# 5. Both views are what their generators render.
if ! $PY scripts/build_brief_pack.py --check; then
  echo "FAIL docs/brief/ is not what scripts/build_brief_pack.py renders"; fail=1
fi
if ! $PY scripts/build_brief_deck.py --check; then
  echo "FAIL docs/deck/brief_deck.pptx is not what scripts/build_brief_deck.py renders"; fail=1
fi

# 6. The deck renderer writes only under docs/deck/.
if grep -nE "write_text|write_bytes|open\([^)]*['\"][wa]" scripts/build_brief_deck.py \
     | grep -vE "out\.write_bytes|DIAGRAM_SIDECAR\.write_text|i\.write_text"; then
  echo "FAIL scripts/build_brief_deck.py writes somewhere other than docs/deck/"; fail=1
fi

# 7. Logs are append-only.
if git diff "$BASE" -- seldon_events.jsonl | grep -q '^-[^-]'; then
  echo "FAIL seldon_events.jsonl lost or changed a line; the log is append-only"; fail=1
fi

if [ "$fail" -eq 0 ]; then echo "PROTECTED PATHS OK"; fi
exit "$fail"
