#!/usr/bin/env python3
"""The one place a write-back to the framework of record goes through. **Zero spend.**

Task `cc_tasks/2026-09-07_scan_hygiene.md` §3, last sentence: *every write-back from now on
regenerates `counts`, and that lives in the shared helper, not in three scripts.* Before this
module there were four writers (`framework_writeback_rules`, `_measured`, `_decisions`,
`add_candidate_indicator`), each recomputing the handful of counters it happened to touch, and
the one nobody recomputed was the one that drifted — which is the defect DD-040 names and
`framework_writeback_rules`'s own docstring records having hit once already.

**What `recount` does NOT do is change any denominator.** The task file that ordered this work
recorded a premise that `counts` disagrees with the file — `constructs: 47, indicators: 48`
against 48 and 49 nodes. It does not. Those two keys are CANDIDATE-EXCLUDED by DD-054 (the
framework does not adopt what the instrument found about itself without the operator), which
`add_candidate_indicator.py` applies and comments in place. Recounting them as totals would
adopt A12 into the framework's headline numbers as a side effect of a hygiene pass — exactly
the silent adoption DD-054 forbids. So each key below states its denominator, and `recount`
reproduces every value the file already holds.

The split between the two groups is not stylistic:

* **candidate-excluded** — counts of what the FRAMEWORK holds. A candidate is recorded and
  reported, and it is not part of the framework until the operator adopts it (DD-054).
* **candidate-inclusive** — counts of what the INSTRUMENT holds. A `MeasurementSpec` exists
  whether or not its indicator has been adopted, and `tests/test_framework_graph.py` asserts
  `measurement_specs == len(specs)` over all of them.

`rules_built` is in neither group and is deliberately absent from `recount`: it is a fact about
`assessment/harness/scan/rules`, not about the JSON, and five spec `rule_id`s name rules that
were never built (`RULE-C4-auto-v0`, `RULE-F2-v0`, `RULE-F3-v0`, `RULE-G1-O-v0`, `RULE-G3-v0`),
so deriving it from the specs would overcount by five. `framework_writeback_rules` owns it;
`check` returns it separately so a gate can still cover it rather than pass it by.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

FRAMEWORK = REPO / "framework" / "ai_readiness_framework.json"
#: A TAGGED shard: `kg/eventlog.replay()` skips tagged shards, and it must, because the
#: framework layer is projected from the JSON (`scripts/load_framework_graph.py`), never from
#: the log. These events are the provenance trail of who changed the record of record and
#: when — not a projection source. Mixing them into the untagged shards would put events into
#: the graph replay that no projector knows how to read.
BATCH = 33
TAG = "framework"
EVENT = "framework_writeback"

#: The DD-054 rule, on the face of the record, so a reader of the JSON never has to find this
#: module to know what a number in `counts` is a count OF.
COUNTS_BASIS = (
    "Node and edge counts of the framework itself (criteria, constructs, indicators, "
    "evidenced_by, evidenced_by_internal, gaps, indicators_measured) EXCLUDE candidate "
    "indicators and their constructs (DD-054: the framework does not adopt what the "
    "instrument found about itself without the operator); candidate_indicators counts them. "
    "Counts of the instrument (measurement_specs, collectors_none_known, "
    "specs_with_recorded_decision) include every spec, adopted or not. rules_built is a fact "
    "about assessment/harness/scan/rules, not about this file. Regenerated by "
    "scripts/framework_writeback.py::recount on every write-back."
)


def _candidate_ids(g: dict) -> set:
    """Nodes DD-054 holds out of the framework: candidate indicators and their constructs."""
    return {n["id"] for n in g["nodes"] if n["properties"].get("status") == "candidate"}


def recount(g: dict) -> dict:
    """Every `counts` key derivable from `nodes`/`edges`, recomputed. See the module docstring
    for why two different denominators are correct rather than a bug."""
    nodes, edges = g["nodes"], g["edges"]
    cand = _candidate_ids(g)

    def n_label(label: str, exclude_candidates: bool) -> int:
        return sum(1 for n in nodes if label in n["labels"]
                   and not (exclude_candidates and n["id"] in cand))

    def n_edge(etype: str) -> int:
        return sum(1 for e in edges if e["type"] == etype and e["from"] not in cand)

    specs = [n["properties"] for n in nodes if "MeasurementSpec" in n["labels"]]
    inds = [n for n in nodes if "AssessmentIndicator" in n["labels"]]
    return {
        # ---- the framework's own content: candidates excluded (DD-054) ----
        "criteria": n_label("AssessmentCriterion", True),
        "constructs": n_label("AssessmentConstruct", True),
        "indicators": n_label("AssessmentIndicator", True),
        "evidenced_by": n_edge("EVIDENCED_BY"),
        "evidenced_by_internal": n_edge("EVIDENCED_BY_INTERNAL"),
        "gaps": sum(1 for n in nodes if n["properties"].get("gap") and n["id"] not in cand),
        "indicators_measured": sum(
            1 for n in inds if n["properties"].get("measurement_status") == "measured"
            and n["id"] not in cand),
        # ---- the instrument: every spec, adopted or not ----
        "measurement_specs": len(specs),
        "collectors_none_known": sum(1 for s in specs if s.get("collector") == "none_known"),
        "specs_with_recorded_decision": sum(1 for s in specs if s.get("decision")),
        # ---- the candidates themselves ----
        "candidate_indicators": len(
            [n for n in inds if n["properties"].get("status") == "candidate"]),
    }


def apply_counts(g: dict) -> dict:
    """Merge `recount` over `g["counts"]` and stamp `counts_basis`. Returns the keys that
    MOVED, so a caller reports drift rather than swallowing it — a counter silently corrected
    is a counter nobody learns was wrong."""
    fresh = recount(g)
    before = dict(g.get("counts") or {})
    moved = {k: [before.get(k), v] for k, v in fresh.items() if before.get(k) != v}
    g.setdefault("counts", {}).update(fresh)
    g["counts_basis"] = COUNTS_BASIS
    return moved


def check(g: dict, built_rule_ids: set | None = None) -> dict:
    """Read-only self-consistency report. `{counts_drift, internal_ref_key_shapes,
    rules_built_expected}`; every value empty or matching means the file agrees with itself."""
    out = {"counts_drift": {k: [(g.get("counts") or {}).get(k), v]
                            for k, v in recount(g).items()
                            if (g.get("counts") or {}).get(k) != v}}
    shapes = sorted({tuple(sorted((e.get("properties") or {}).keys()))
                     for e in g["edges"] if e["type"] == "EVIDENCED_BY_INTERNAL"})
    prefixed = all(str(e["to"]).startswith("internal:") for e in g["edges"]
                   if e["type"] == "EVIDENCED_BY_INTERNAL")
    out["internal_ref_key_shapes"] = [list(s) for s in shapes]
    out["internal_refs_all_prefixed"] = prefixed
    if built_rule_ids is not None:
        out["rules_built_expected"] = len(built_rule_ids)
        out["rules_built_recorded"] = (g.get("counts") or {}).get("rules_built")
    return out


def save(g: dict, script: str, task: str, changes: dict, dry_run: bool = False,
         path: Path | None = None) -> dict:
    """Write the framework JSON and append the `framework_writeback` event that says who did.

    The event carries the sha256 of the bytes written, so "which revision of the record does
    this projection correspond to" is answerable from the log rather than from a commit
    message. A dry run writes neither.
    """
    path = path or FRAMEWORK
    moved = apply_counts(g)
    body = json.dumps(g, indent=1, ensure_ascii=False) + "\n"
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    record = {"event_type": EVENT, "script": script, "task": task,
              "framework_path": str(path.relative_to(REPO)), "framework_sha256": digest,
              "changes": changes, "counts_moved": moved, "counts": g["counts"]}
    if dry_run:
        return {**record, "written": False}
    path.write_text(body, encoding="utf-8")
    from kg import eventlog
    event_id = eventlog.append(record, batch=BATCH, tag=TAG)
    return {**record, "written": True, "event_id": event_id,
            "shard": f"events/batch-{BATCH:03d}_{TAG}.jsonl"}
