#!/usr/bin/env python3
"""Regenerate assessment/config/g1_pilot.toml from the G1 fixture files (task
2026-09-03_g1_eval_v1_parser_fullgrid_errata step 2).

The schedule is the FULL grid, pre-registered before any call: for every passage one
`indirect` step (every proposition sharing the passage is scored from that one response),
and for every (proposition, qualifier class) one `direct` step. Development propositions
first, held-out propositions after — the runner's `--split` selects which half is elicited,
so the holdout stays sealed until the parser freeze (step 5). Steps are ordered
passage-by-passage (indirect, then its directs) so a prefix reached under a ceiling still
covers both modes.

    python3 scripts/gen_g1_schedule.py [--floor 34000]

Prints the step count and the token cost at the g1_eval floor.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "assessment"))

from harness.g1_fixtures import load_fixture_set  # noqa: E402

FIX = REPO / "assessment" / "tests" / "fixtures" / "g1"
OUT = REPO / "assessment" / "config" / "g1_pilot.toml"

HEADER = """# G1 EVAL run schedule — GENERATED by scripts/gen_g1_schedule.py from the fixture files
# (fixture_version {fixture_version}); do not hand-edit. Task 2026-09-03_g1_eval_v1_parser_fullgrid_errata
# step 2 (supersedes the hand-written v0 prefix schedule of task 2026-09-02, which the v0 RESULT
# records).
#
# The FULL grid, pre-registered before any call: one `indirect` step per passage (every
# proposition sharing the passage is scored from that one response) and one `direct` step per
# (proposition, qualifier class). Development set first, held-out set after; the runner's
# --split selects the half to elicit, and a slot whose evidence file exists is reused, never
# re-elicited. Ordered passage-by-passage so any prefix covers both modes.
#
# Size: {n_dev} development steps + {n_hold} held-out steps = {n_total} calls;
# at the g1_eval floor of {floor:,} tokens/call the whole grid needs {cost:,} tokens
# (development {cost_dev:,}; held-out {cost_hold:,}). Per-run ceiling declared by the runner.
"""


def steps_for(fs, seen: set) -> list:
    """`seen` carries passages already scheduled by an earlier set: a passage shared by
    the two splits is elicited once (in the set where it first appears) and every
    proposition on it, from either split, is scored from that one response."""
    out = []
    for p in fs.propositions:
        if p.passage_id not in seen:
            seen.add(p.passage_id)
            out.append(("indirect", p.passage_id, None, None))
            for q in fs.by_passage(p.passage_id):
                for cls in sorted({x.cls.value for x in q.qualifiers}):
                    out.append(("direct", None, q.id, cls))
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--floor", type=int, default=34000)
    a = ap.parse_args(argv)
    dev = load_fixture_set(FIX / "propositions.yaml")
    hold = load_fixture_set(FIX / "propositions_holdout.yaml")
    fv = "unknown"
    first = (FIX / "propositions.yaml").read_text(encoding="utf-8").splitlines()[0]
    if first.startswith("# fixture_version:"):
        fv = first.split(":", 1)[1].strip()
    seen: set = set()
    d, h = steps_for(dev, seen), steps_for(hold, seen)
    lines = [HEADER.format(fixture_version=fv, n_dev=len(d), n_hold=len(h), n_total=len(d) + len(h),
                           floor=a.floor, cost=(len(d) + len(h)) * a.floor, cost_dev=len(d) * a.floor,
                           cost_hold=len(h) * a.floor)]
    for label, steps in (("development set (propositions.yaml)", d), ("held-out set (propositions_holdout.yaml)", h)):
        lines.append(f"# --- {label} ---\n")
        for kind, pg, pid, cls in steps:
            if kind == "indirect":
                lines.append(f'[[steps]]\nkind = "indirect"\npassage = "{pg}"\n')
            else:
                lines.append(f'[[steps]]\nkind = "direct"\nproposition = "{pid}"\nqualifier = "{cls}"\n')
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"schedule: {len(d)} dev + {len(h)} holdout = {len(d) + len(h)} steps; "
          f"{(len(d) + len(h)) * a.floor:,} tokens at floor {a.floor:,} "
          f"(dev {len(d) * a.floor:,}, holdout {len(h) * a.floor:,}) -> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
