#!/usr/bin/env python3
"""Regenerate assessment/config/g1_pilot.toml from the G1 fixture files (task
2026-09-03_g1_eval_v1_parser_fullgrid_errata step 2).

The schedule is the FULL grid, pre-registered before any call: for every passage one
`indirect` step (every proposition sharing the passage is scored from that one response),
and for every (proposition, qualifier class) one `direct` step. Development propositions
first, held-out propositions after — the runner's `--split` selects which half is elicited,
so the holdout stays sealed until the parser freeze (step 5). Steps are ordered
passage-by-passage (indirect, then its directs) so a prefix reached under a ceiling still
covers both modes.

    python3 scripts/gen_g1_schedule.py [--floor 34000]

Prints the step count and the token cost at the g1_eval floor.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "assessment"))

from harness.g1_fixtures import load_fixture_set  # noqa: E402

FIX = REPO / "assessment" / "tests" / "fixtures" / "g1"
OUT = REPO / "assessment" / "config" / "g1_pilot.toml"

HEADER = """# G1 EVAL run schedule — GENERATED by scripts/gen_g1_schedule.py from the fixture files
# (fixture_version {fixture_version}); do not hand-edit. Task 2026-09-03_g1_eval_v1_parser_fullgrid_errata
# step 2 (supersedes the hand-written v0 prefix schedule of task 2026-09-02, which the v0 RESULT
# records).
#
# The FULL grid, pre-registered before any call: one `indirect` step per passage (every
# proposition sharing the passage is scored from that one response) and one `direct` step per
# (proposition, qualifier class). Development set first, held-out set after; the runner's
# --split selects the half to elicit, and a slot whose evidence file exists is reused, never
# re-elicited. Ordered passage-by-passage so any prefix covers both modes.
#
# Size: {n_dev} development steps + {n_hold} held-out steps = {n_total} calls;
# at the g1_eval floor of {floor:,} tokens/call the whole grid needs {cost:,} tokens
# (development {cost_dev:,}; held-out {cost_hold:,}). Per-run ceiling declared by the runner.
"""


def steps_for(fs, seen: set) -> list:
    """`seen` carries passages already scheduled by an earlier set: a passage shared by
    the two splits is elicited once (in the set where it first appears) and every
    proposition on it, from either split, is scored from that one response."""
    out = []
    done_passages: set = set()
    for p in fs.propositions:
        if p.passage_id in done_passages:
            continue
        done_passages.add(p.passage_id)
        if p.passage_id not in seen:
            seen.add(p.passage_id)
            out.append(("indirect", p.passage_id, None, None))
        # Direct steps for EVERY proposition of this set on the passage, whether or not the
        # indirect call was scheduled by the other set.
        for q in fs.by_passage(p.passage_id):
            for cls in sorted({x.cls.value for x in q.qualifiers}):
                out.append(("direct", None, q.id, cls))
    return out


# ---------------------------------------------------------------- v2 (task 2026-09-03_g1_eval_v2 step 3)
FIX_V2 = FIX / "v2"
OUT_V2 = REPO / "assessment" / "config" / "g1_v2_schedule.toml"
COMPRESSION = ("none", "short", "tight")

HEADER_V2 = """# G1 EVAL v2 run schedule — GENERATED by scripts/gen_g1_schedule.py --version v2 from the v1 and v2
# fixture files (v1 {fv1}; v2 {fv2}); do not hand-edit. Task
# 2026-09-03_g1_eval_v2_product_surfaces_compression step 3 (designs D9, D12, D13).
#
# Split BY PASSAGE (a passage belongs to exactly one split). The twelve v1 passages shared by
# the v1 dev and holdout files carry propositions of both; their `none` indirect responses were
# development evidence the parser author read (the v2 step-1 seal recompute), so in v2 every
# shared passage — and every proposition on it, whichever v1 file it came from — belongs to
# DEV (`split_origin` records where each came from). The v2 product-surface passages are
# already disjoint by construction.
#
# indirect = passages x {{none, short, tight}}; direct = (proposition, family) under the
# unchanged direct template. The control arm (D13) is the holdout schedule again under the
# control consumer; the runner selects it with --consumer control. A `none` indirect slot or a
# direct slot whose prompt text is byte-identical to a v0-epoch slot for the same model reuses
# that evidence (D12); the counts below say how many calls that saves.
#
# Size at the g1_eval floor of {floor:,} tokens/call:
#   dev      {n_dev:4d} steps ({dev_new:4d} new calls, {dev_reuse:3d} reusable v1 slots) = {cost_dev:>10,} tokens new
#   holdout  {n_hold:4d} steps ({hold_new:4d} new calls, {hold_reuse:3d} reusable v1 slots) = {cost_hold:>10,} tokens new
#   control  {n_hold:4d} steps (all new: a different model)                       = {cost_ctl:>10,} tokens
#   total new calls {total_new} = {cost_total:,} tokens (task cap 8,000,000; per-run ceiling 2,000,000)
#   without v1 reuse the grid would be {total_all} calls = {cost_all:,} tokens.
"""


def _family_of(cls: str) -> str:
    from harness.records import FAMILY_OF
    return FAMILY_OF[cls]


def v2_split():
    """Passages and propositions by split under the by-passage rule; returns
    (dev_passages, hold_passages, props) with props: id -> (split, proposition, origin)."""
    v1_dev = load_fixture_set(FIX / "propositions.yaml")
    v1_hold = load_fixture_set(FIX / "propositions_holdout.yaml")
    v2_dev = load_fixture_set(FIX_V2 / "propositions.yaml")
    v2_hold = load_fixture_set(FIX_V2 / "propositions_holdout.yaml")
    dev_pass = {p.passage_id for p in v1_dev.propositions}
    shared = dev_pass & {p.passage_id for p in v1_hold.propositions}
    props = {}
    passages = {}
    for fs, origin in ((v1_dev, "v1_dev"), (v1_hold, "v1_holdout"), (v2_dev, "v2_dev"), (v2_hold, "v2_holdout")):
        for p in fs.propositions:
            if origin == "v1_holdout" and p.passage_id in shared:
                split = "dev"
            else:
                split = "dev" if origin.endswith("dev") else "holdout"
            props[p.id] = (split, p, origin)
            passages.setdefault(p.passage_id, {"split": split, "props": [], "origin": origin,
                                               "surface_type": p.surface_type})
            passages[p.passage_id]["props"].append(p.id)
            if passages[p.passage_id]["split"] != split:
                raise SystemExit(f"FATAL: passage {p.passage_id} would sit in both splits")
    return passages, props, sorted(shared)


def v2_steps(passages: dict, props: dict, split: str) -> list:
    out = []
    for pg, info in passages.items():
        if info["split"] != split:
            continue
        for comp in COMPRESSION:
            out.append({"kind": "indirect", "passage": pg, "compression": comp, "propositions": list(info["props"]),
                        "surface_type": info["surface_type"], "reusable": comp == "none" and info["origin"].startswith("v1")})
        for pid in info["props"]:
            p = props[pid][1]
            fams = []
            for q in p.qualifiers:
                f = _family_of(q.cls.value)
                if f not in fams:
                    fams.append(f)
            for f in fams:
                asked = next(q.cls.value for q in p.qualifiers if _family_of(q.cls.value) == f)
                out.append({"kind": "direct", "proposition": pid, "family": f, "qualifier": asked,
                            "surface_type": p.surface_type, "reusable": props[pid][2].startswith("v1")})
    return out


def write_v2(floor: int) -> int:
    passages, props, shared = v2_split()
    dev, hold = v2_steps(passages, props, "dev"), v2_steps(passages, props, "holdout")
    fv1 = (FIX / "propositions.yaml").read_text(encoding="utf-8").splitlines()[0].split(":", 1)[1].strip()
    fv2 = (FIX_V2 / "propositions.yaml").read_text(encoding="utf-8").splitlines()[0].split(":", 1)[1].strip()
    dev_reuse = sum(1 for s in dev if s["reusable"])
    hold_reuse = sum(1 for s in hold if s["reusable"])
    dev_new, hold_new = len(dev) - dev_reuse, len(hold) - hold_reuse
    total_new = dev_new + hold_new + len(hold)
    lines = [HEADER_V2.format(fv1=fv1, fv2=fv2, floor=floor, n_dev=len(dev), dev_new=dev_new, dev_reuse=dev_reuse,
                              cost_dev=dev_new * floor, n_hold=len(hold), hold_new=hold_new, hold_reuse=hold_reuse,
                              cost_hold=hold_new * floor, cost_ctl=len(hold) * floor, total_new=total_new,
                              cost_total=total_new * floor, total_all=len(dev) + 2 * len(hold),
                              cost_all=(len(dev) + 2 * len(hold)) * floor)]
    lines.append(f"# shared v1 passages assigned to dev: {', '.join(shared)}\n")
    for label, steps, split in (("development", dev, "dev"), ("held-out (Opus holdout run and the control arm)", hold, "holdout")):
        lines.append(f"# --- {label} ---\n")
        for s in steps:
            if s["kind"] == "indirect":
                lines.append(f'[[steps]]\nkind = "indirect"\nsplit = "{split}"\npassage = "{s["passage"]}"\ncompression = "{s["compression"]}"\n'
                             f'surface_type = "{s["surface_type"]}"\nreusable = {str(s["reusable"]).lower()}\n')
            else:
                lines.append(f'[[steps]]\nkind = "direct"\nsplit = "{split}"\nproposition = "{s["proposition"]}"\nfamily = "{s["family"]}"\n'
                             f'qualifier = "{s["qualifier"]}"\nsurface_type = "{s["surface_type"]}"\nreusable = {str(s["reusable"]).lower()}\n')
    OUT_V2.write_text("".join(lines), encoding="utf-8")
    print(f"v2 schedule: dev {len(dev)} steps ({dev_new} new), holdout {len(hold)} ({hold_new} new), control {len(hold)} (all new); "
          f"total new calls {total_new} = {total_new * floor:,} tokens at floor {floor:,} "
          f"(without reuse {(len(dev) + 2 * len(hold)) * floor:,}) -> {OUT_V2.relative_to(REPO)}")
    by_surface = {}
    for s in dev + hold:
        by_surface[(s["surface_type"], s["kind"])] = by_surface.get((s["surface_type"], s["kind"]), 0) + 1
    for k, n in sorted(by_surface.items()):
        print(f"  {k[0]:14s} {k[1]:8s} {n}")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--floor", type=int, default=34000)
    ap.add_argument("--version", choices=["v1", "v2"], default="v1")
    a = ap.parse_args(argv)
    if a.version == "v2":
        return write_v2(a.floor)
    dev = load_fixture_set(FIX / "propositions.yaml")
    hold = load_fixture_set(FIX / "propositions_holdout.yaml")
    fv = "unknown"
    first = (FIX / "propositions.yaml").read_text(encoding="utf-8").splitlines()[0]
    if first.startswith("# fixture_version:"):
        fv = first.split(":", 1)[1].strip()
    seen: set = set()
    d, h = steps_for(dev, seen), steps_for(hold, seen)
    lines = [HEADER.format(fixture_version=fv, n_dev=len(d), n_hold=len(h), n_total=len(d) + len(h),
                           floor=a.floor, cost=(len(d) + len(h)) * a.floor, cost_dev=len(d) * a.floor,
                           cost_hold=len(h) * a.floor)]
    for label, steps in (("development set (propositions.yaml)", d), ("held-out set (propositions_holdout.yaml)", h)):
        lines.append(f"# --- {label} ---\n")
        for kind, pg, pid, cls in steps:
            if kind == "indirect":
                lines.append(f'[[steps]]\nkind = "indirect"\npassage = "{pg}"\n')
            else:
                lines.append(f'[[steps]]\nkind = "direct"\nproposition = "{pid}"\nqualifier = "{cls}"\n')
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"schedule: {len(d)} dev + {len(h)} holdout = {len(d) + len(h)} steps; "
          f"{(len(d) + len(h)) * a.floor:,} tokens at floor {a.floor:,} "
          f"(dev {len(d) * a.floor:,}, holdout {len(h) * a.floor:,}) -> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
