#!/usr/bin/env python3
"""The recollection's delta table: rj4, rj5 and the recollection, per surface and leg. **No network.**

`cc_tasks/2026-10-06_absence_verdicts_recollection_v2.md` decision 5, widened to all twelve legs
by ADDENDUM_01 amendment 3: "For every body and each recollected leg: the rj4 verdict, the rj5
verdict, this cycle's verdict." The named cases are computed here, not described: Census ACS A2,
the rj4 D4 rows that said "no public data.json catalog served on this host", and the A9, D1 and
F4 rows that rj5 moved to `error` on no declaration at all.

Read-only over three stored payloads; writes one JSON (the full table, every reason) and one
markdown summary. Every count in the summary is computed from the JSON's rows.

    /opt/anaconda3/bin/python3 scripts/recollection_delta.py
"""
from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
STATE = REPO / "state"
TASK = "cc_tasks/2026-10-06_absence_verdicts_recollection_v2.md"
RJ4, RJ5, NEW = "scan_2026-09-10_rj4", "scan_2026-09-10_rj5", "scan_2026-10-06_recollect"
COMPOSITE = "scan_2026-10-06_composite_b"
OUT_JSON = STATE / "recollection_delta_2026-10-06.json"
OUT_MD = REPO / "docs" / "research" / "2026-10-06_recollection_delta.md"
#: The rj4 reason that made a D4 row one of the audit's "no catalog" rows (C-04).
NO_CATALOG = "no public data.json catalog served on this host"
ACS = "scan-census-flagship-2-american-community-survey-acs"
D4_FAMILY = ("D4", "B1", "B4", "D3", "G4")
SHORT = {"pass": "P", "fail": "F", "error": "E", "not_applicable": "N", None: "-"}


def load(c: str) -> dict:
    return json.loads((STATE / f"{c}.json").read_text(encoding="utf-8"))


def index(p: dict) -> dict:
    return {(f["target_doc_id"], f["leg"]): f for f in p["findings_detail"]}


def table() -> dict:
    new = load(NEW)
    legs = list(new["legs_collected"])
    agency = {r["doc_id"]: r["agency"] for r in new["matrix"]}
    i4, i5, i6 = index(load(RJ4)), index(load(RJ5)), index(new)
    rows = []
    for doc in sorted(agency, key=lambda d: (agency[d], d)):
        for leg in legs:
            cells = [x.get((doc, leg)) for x in (i4, i5, i6)]
            if not any(cells):
                continue
            rows.append({"body": agency[doc], "surface": doc, "leg": leg,
                         **{k: (c or {}).get("verdict") for k, c in zip(("rj4", "rj5", "new"),
                                                                       cells)},
                         **{f"{k}_reason": (c or {}).get("reason") for k, c in
                            zip(("rj4", "rj5", "new"), cells)},
                         "new_finding_id": (cells[2] or {}).get("finding_id")})
    return {"task": TASK, "cycles": {"rj4": RJ4, "rj5": RJ5, "new": NEW}, "legs": legs,
            "rows": rows}


def counts(rows: list, key: str) -> dict:
    out: dict = {}
    for r in rows:
        out.setdefault(r["leg"], collections.Counter())[r[key]] += 1
    return {l: dict(c) for l, c in out.items()}


def summary(t: dict) -> str:
    rows, legs = t["rows"], t["legs"]
    vs = ("pass", "fail", "error", "not_applicable")
    c5, c6 = counts(rows, "rj5"), counts(rows, "new")
    out = [f"# Recollection delta: `{RJ4}` → `{RJ5}` → `{NEW}`", "",
           f"Generated by `scripts/recollection_delta.py` from the three payloads in `state/` "
           f"({TASK}, decision 5 and ADDENDUM_01 amendment 3). The full table, one row per "
           f"surface and leg with every reason, is `{OUT_JSON.relative_to(REPO)}`; every count "
           f"below is computed from it. {len(rows)} cells over "
           f"{len({r['surface'] for r in rows})} surfaces and {len(legs)} legs.", "",
           "## Verdict counts per leg, before (rj5) and after (the recollection)", "",
           "| leg | rj5 pass | rj5 fail | rj5 error | new pass | new fail | new error | new n/a |",
           "|---|---|---|---|---|---|---|---|"]
    for l in legs:
        a, b = c5.get(l, {}), c6.get(l, {})
        out.append(f"| {l} | {a.get('pass', 0)} | {a.get('fail', 0)} | {a.get('error', 0)} | "
                   f"{b.get('pass', 0)} | {b.get('fail', 0)} | {b.get('error', 0)} | "
                   f"{b.get('not_applicable', 0)} |")
    out += ["", "## Transitions per leg (rj4 → rj5 → new), as P/F/E/N", ""]
    for l in legs:
        tr = collections.Counter(f"{SHORT[r['rj4']]}{SHORT[r['rj5']]}{SHORT[r['new']]}"
                                 for r in rows if r["leg"] == l)
        out.append(f"- **{l}**: " + ", ".join(f"`{k}` {n}" for k, n in sorted(tr.items())))
    out += ["", "## Per body: rj4 → rj5 → new, counted over the body's surfaces", "",
            "| body | " + " | ".join(legs) + " |", "|---|" + "---|" * len(legs)]
    for b in sorted({r["body"] for r in rows}):
        cells = []
        for l in legs:
            tr = collections.Counter(f"{SHORT[r['rj4']]}{SHORT[r['rj5']]}{SHORT[r['new']]}"
                                     for r in rows if r["body"] == b and r["leg"] == l)
            cells.append(" ".join(f"{k}×{n}" if n > 1 else k for k, n in sorted(tr.items()))
                         or "")
        out.append(f"| {b} | " + " | ".join(cells) + " |")
    out += ["", "## The named cases", ""]
    acs = [r for r in rows if r["surface"] == ACS and r["leg"] == "A2"]
    for r in acs:
        out.append(f"**Census ACS A2** (`{ACS}`): rj4 `{r['rj4']}` (\"{r['rj4_reason']}\"); "
                   f"rj5 `{r['rj5']}` (\"{r['rj5_reason']}\"); now `{r['new']}` "
                   f"(\"{r['new_reason']}\"). The composite of record shows the rj5 verdict: A2 is "
                   f"withheld from its overlay (last section).")
    nc = [r for r in rows if r["leg"] in D4_FAMILY and r["rj4"] == "fail"
          and NO_CATALOG in (r["rj4_reason"] or "")]
    out += ["", f"**The \"no catalog\" rows.** {sum(1 for r in nc if r['leg'] == 'D4')} D4 rows "
                f"said \"{NO_CATALOG}\" under rj4 ({len(nc)} across the D4 family). What each "
                f"became under the recollection:", ""]
    for l in D4_FAMILY:
        sub = [r for r in nc if r["leg"] == l]
        if sub:
            out.append(f"- {l}: " + ", ".join(f"`{k}` {n}" for k, n in sorted(
                collections.Counter(r["new"] for r in sub).items())))
    out += ["", "**A9, D1 and F4: the rows rj5 moved from `fail` to `error` on no declaration.** Per leg, "
                "what the recollection made of them:", ""]
    for l in ("A9", "D1", "F4"):
        # rj5 moved every one of these from `fail` to `error` because nothing was declared for
        # the leg to search (rules RESULT §2: 40 per leg); the selector is the move itself.
        sub = [r for r in rows if r["leg"] == l and r["rj4"] == "fail" and r["rj5"] == "error"]
        out.append(f"- {l}: {len(sub)} rows; now " + ", ".join(
            f"`{k}` {n}" for k, n in sorted(collections.Counter(r["new"] for r in sub).items())))
    comp = json.loads((STATE / f"{COMPOSITE}.json").read_text(encoding="utf-8"))
    withheld = comp["composed_of"]["overlay"].get("withheld") or {}
    out += ["", f"## What the composite of record shows (`{COMPOSITE}`)", "",
            f"The composite takes the recollection's verdict on "
            f"{', '.join(comp['composed_of']['overlay']['legs'])} and `{RJ5}`'s on every other "
            f"leg. Withheld from the overlay, with the reason stated on `composed_of`:", ""]
    for l, why in withheld.items():
        passes = [r for r in rows if r["leg"] == l and r["new"] == "pass"]
        out.append(f"- **{l}** ({len(passes)} recollected passes, on "
                   f"{', '.join(sorted({r['body'] for r in passes}))}): {why}")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="refuse if the outputs would change")
    a = ap.parse_args(argv)
    t = table()
    js = json.dumps(t, indent=1) + "\n"
    md = summary(t)
    if a.check:
        bad = [p for p, s in ((OUT_JSON, js), (OUT_MD, md))
               if not p.exists() or p.read_text(encoding="utf-8") != s]
        print("CHECK:", "PASS" if not bad else f"FAIL {[str(p) for p in bad]}")
        return 1 if bad else 0
    OUT_JSON.write_text(js, encoding="utf-8")
    OUT_MD.write_text(md, encoding="utf-8")
    print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
