#!/usr/bin/env python3
"""G1 EVAL v2 runner (task 2026-09-03_g1_eval_v2_product_surfaces_compression steps 4, 5b, 5c).

Walks the PRE-REGISTERED v2 schedule (assessment/config/g1_v2_schedule.toml, generated by
scripts/gen_g1_schedule.py --version v2): indirect calls per passage x compression level
(D12) and one direct call per (proposition, family) (D9), for ONE split under ONE pinned
consumer — the pinned consumer (`--consumer consumer`) or the single control arm
(`--consumer control`, D13, holdout only) — through the repo choke point
(kg/extraction/model_stub.invoke: DD-007 OAuth-only gate, DD-022 reserve-before-dispatch,
invariant-5 model-identity gate). Evidence is written BEFORE anything is scored, to
assessment/evidence/g1/v2/<dev|holdout|control>/; a slot that already has a response —
in the run's directory, or (pinned consumer, `none` / direct slots only) a byte-identical
v0-epoch slot in assessment/evidence/g1[/holdout] — is reused, never re-elicited (D12).

The run is declared on the shared spend ledger with the task's stated ceiling
(`--ceiling-tokens`, REQUIRED; 2,000,000 in this task; the schedule is split across
declared runs when it exceeds that at the floor). A refusal is a clean stop (exit 0).
`--dry-run` renders every prompt, counts calls and reusable slots, and spends nothing.

    /opt/anaconda3/bin/python3 scripts/run_g1_v2.py --split dev --ceiling-tokens 2000000 --run-id g1_eval_v2_dev_2026-09-03 [--dry-run] [--max-calls N]
    /opt/anaconda3/bin/python3 scripts/run_g1_v2.py --split holdout --consumer control --ceiling-tokens 2000000 --run-id g1_eval_v2_control_2026-09-03

Outputs: assessment/results/g1_v2_run_<run_id>.json (family records + rollup G1 block + the
schedule walk + the D14 expectation tests over this run's records), and a printed report.
Scoring at run time uses the parser/scorer in the working tree; the authoritative re-score
is scripts/rescore_g1_v2.py after the g1-v2-frozen commit.
"""
from __future__ import annotations

import argparse
import json
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ASSESSMENT = REPO / "assessment"
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(ASSESSMENT))

from harness.consumers import ClaudeCLIConsumer, load_consumer_config  # noqa: E402
from harness.g1_expectations import expectations_v2  # noqa: E402
from harness.g1_fixtures import load_fixture_set  # noqa: E402
from harness.probes.g1_preservation import SCORER_VERSION, PreservationProbe, load_prompts  # noqa: E402
from harness.probes._g1_parse import PARSER_VERSION  # noqa: E402
from harness.rollup import g1_block  # noqa: E402
from kg import spend  # noqa: E402
from kg.extraction import model_stub  # noqa: E402

CONFIG = ASSESSMENT / "config"
FIX = ASSESSMENT / "tests" / "fixtures" / "g1"
EVIDENCE = ASSESSMENT / "evidence" / "g1"
RESULTS = ASSESSMENT / "results"
TASK = "cc_tasks/2026-09-03_g1_eval_v2_product_surfaces_compression.md"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_schedule(path: Path) -> list:
    with path.open("rb") as fh:
        d = tomllib.load(fh)
    steps = d.get("steps")
    if not steps:
        raise SystemExit(f"FATAL: no [[steps]] in {path}")
    for i, s in enumerate(steps):
        if s.get("split") not in ("dev", "holdout"):
            raise SystemExit(f"FATAL: step {i} without split")
        if s.get("kind") == "indirect" and not (s.get("passage") and s.get("compression")):
            raise SystemExit(f"FATAL: step {i} indirect without passage/compression")
        if s.get("kind") == "direct" and not (s.get("proposition") and s.get("family") and s.get("qualifier")):
            raise SystemExit(f"FATAL: step {i} direct without proposition/family/qualifier")
        if s.get("kind") not in ("indirect", "direct"):
            raise SystemExit(f"FATAL: step {i} unknown kind {s.get('kind')!r}")
    return steps


def load_all_fixtures():
    """props: id -> proposition; passages: id -> [propositions]; meta: passage id -> passage_meta."""
    props, passages, meta = {}, {}, {}
    for path in (FIX / "propositions.yaml", FIX / "propositions_holdout.yaml",
                 FIX / "v2" / "propositions.yaml", FIX / "v2" / "propositions_holdout.yaml"):
        fs = load_fixture_set(path)
        for p in fs.propositions:
            if p.id in props:
                raise SystemExit(f"FATAL: proposition id {p.id} appears in two fixture files")
            props[p.id] = p
            passages.setdefault(p.passage_id, []).append(p)
        for pid, m in fs.passage_meta.items():
            meta[pid] = m
    return props, passages, meta


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ceiling-tokens", type=int, required=True,
                    help="per-run ceiling declared on the spend ledger (the task file's stated ceiling)")
    ap.add_argument("--run-id", default=None)
    ap.add_argument("--split", choices=["dev", "holdout"], required=True)
    ap.add_argument("--consumer", choices=["consumer", "control"], default="consumer",
                    help="the pinned consumer, or the single control arm (holdout only, D13)")
    ap.add_argument("--dry-run", action="store_true", help="render prompts, count calls, spend nothing")
    ap.add_argument("--max-calls", type=int, default=0, help="0 = walk the whole schedule (until refused)")
    ap.add_argument("--schedule", default=str(CONFIG / "g1_v2_schedule.toml"))
    ap.add_argument("--evidence-dir", default=None,
                    help="evidence directory (default assessment/evidence/g1/v2/<split|control>)")
    ap.add_argument("--no-legacy-reuse", action="store_true",
                    help="do not reuse byte-identical v0-epoch evidence (default: reuse for the pinned consumer)")
    a = ap.parse_args(argv)

    model_stub.guard_no_api_key()
    if a.consumer == "control" and a.split != "holdout":
        raise SystemExit("FATAL: the control arm runs on the holdout grid only (D13)")
    consumer_cfg = load_consumer_config(CONFIG / "g1_consumer.toml", table=a.consumer)
    prompts = load_prompts(CONFIG / "g1_prompts.toml")
    steps = [s for s in load_schedule(Path(a.schedule)) if s["split"] == a.split]
    props, passages, meta = load_all_fixtures()
    for s in steps:
        if s["kind"] == "indirect" and s["passage"] not in passages:
            raise SystemExit(f"FATAL: schedule names unknown passage {s['passage']!r}")
        if s["kind"] == "direct" and s["proposition"] not in props:
            raise SystemExit(f"FATAL: schedule names unknown proposition {s['proposition']!r}")

    spend_cfg = spend._spend_config()
    floor = int(spend_cfg["call_class_floors"].get(consumer_cfg.call_class, 0))
    if not floor:
        raise SystemExit(f"FATAL: controls.yaml has no call_class_floors.{consumer_cfg.call_class}")
    daily = int(spend_cfg["daily_tokens"])
    if a.ceiling_tokens > daily:
        raise SystemExit(f"FATAL: ceiling {a.ceiling_tokens:,} exceeds the standing daily band {daily:,}; stop and report")

    arm = "control" if a.consumer == "control" else a.split
    run_id = a.run_id or spend.default_run_id(f"g1_eval_v2_{arm}")
    evidence_dir = Path(a.evidence_dir).resolve() if a.evidence_dir else (EVIDENCE / "v2" / arm)
    legacy = () if (a.no_legacy_reuse or a.consumer == "control") else (EVIDENCE, EVIDENCE / "holdout")
    probe = PreservationProbe(prompts, evidence_dir, legacy_evidence_dirs=legacy)
    model_id = consumer_cfg.model_id

    # what the walk will do: reuse or call
    plan = []
    for s in steps:
        if s["kind"] == "indirect":
            call_id = f"{s['passage']}.indirect"
            existing = probe.existing_evidence(call_id, "indirect", None, model_id, compression=s["compression"])
        else:
            existing = probe.existing_evidence(s["proposition"], "direct", s["qualifier"], model_id)
        plan.append((s, existing))
    n_calls = sum(1 for _, e in plan if e is None)
    n_reuse = len(plan) - n_calls
    report = {"task": TASK, "run_id": run_id, "split": a.split, "consumer": a.consumer, "model_id": model_id,
              "evidence_dir": str(evidence_dir.relative_to(REPO)) if evidence_dir.is_relative_to(REPO) else str(evidence_dir),
              "legacy_evidence_dirs": [str(Path(d).relative_to(REPO)) for d in legacy],
              "started_at": _now(), "prompt_epoch": prompts.prompt_epoch,
              "parser_version": PARSER_VERSION, "scorer_version": SCORER_VERSION,
              "ceiling_tokens": a.ceiling_tokens, "call_class": consumer_cfg.call_class, "call_class_floor": floor,
              "schedule_steps": len(plan), "schedule_calls": n_calls, "schedule_reused": n_reuse,
              "schedule_tokens_at_floor": n_calls * floor, "dry_run": a.dry_run, "walk": [], "records": []}
    print(f"run {run_id} ({a.split}, {a.consumer}={model_id}): {len(plan)} steps, {n_calls} calls, {n_reuse} reusable; "
          f"at the {consumer_cfg.call_class} floor of {floor:,} tokens the calls need {n_calls * floor:,} vs ceiling {a.ceiling_tokens:,}")
    if a.dry_run:
        for s, existing in plan:
            if s["kind"] == "indirect":
                prompt = probe.render_prompt(passages[s["passage"]][0], "indirect", compression=s["compression"])
            else:
                prompt = probe.render_prompt(props[s["proposition"]], "direct", s["qualifier"])
            report["walk"].append({**s, "prompt_chars": len(prompt), "status": "reuse" if existing else "dry_run",
                                   "evidence_path": (str(Path(existing.evidence_path).relative_to(REPO)) if existing else None)})
        out = RESULTS / f"g1_v2_run_{run_id}_dryrun.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"dry run written: {out.relative_to(REPO)}")
        return 0

    ledger = spend.default_ledger()
    ledger.declare(run_id, a.ceiling_tokens, declared_by=f"scripts/run_g1_v2.py ({TASK})", call_class=consumer_cfg.call_class)
    spend.set_current_run(run_id)
    consumer = ClaudeCLIConsumer(consumer_cfg)
    records = []
    stop_reason = "schedule_complete"
    made = 0
    for i, (s, existing) in enumerate(plan):
        if a.max_calls and made >= a.max_calls and existing is None:
            stop_reason = f"max_calls={a.max_calls}"
            break
        try:
            if s["kind"] == "indirect":
                plist = passages[s["passage"]]
                call_id = f"{s['passage']}.indirect"
                el = existing or probe.elicit(consumer, plist[0], "indirect", call_id=call_id, compression=s["compression"])
                new = []
                for p in plist:
                    el_p = el.__class__(**{**el.__dict__, "proposition_id": p.id})
                    new.extend(probe.records(el_p, p, compression=s["compression"], passage_meta=meta.get(p.passage_id), siblings=plist))
            else:
                p = props[s["proposition"]]
                el = existing or probe.elicit(consumer, p, "direct", s["qualifier"])
                new = probe.records(el, p, only_family=s["family"], passage_meta=meta.get(p.passage_id), siblings=passages[p.passage_id])
            records.extend(new)
            status = "reused_evidence" if existing is not None else "ok"
            if existing is None:
                made += 1
            report["walk"].append({**s, "status": status, "evidence_path": str(Path(el.evidence_path).relative_to(REPO)),
                                   "usage": el.usage, "n_records": len(new), "evidence_epoch": el.prompt_epoch})
            label = s.get("passage") or s["proposition"]
            if existing is not None:
                print(f"  [{i + 1}/{len(plan)}] {s['kind']} {label} {s.get('compression') or s.get('family')} -> reused {Path(el.evidence_path).name}; {len(new)} record(s)")
                continue
            print(f"  [{i + 1}/{len(plan)}] {s['kind']} {label} {s.get('compression') or s.get('family')} -> {len(new)} record(s); "
                  f"usage {el.usage.get('inputTokens')}/{el.usage.get('outputTokens')} "
                  f"(+cache {el.usage.get('cacheCreationInputTokens')}/{el.usage.get('cacheReadInputTokens')})")
        except spend.SpendRefusalStop as exc:
            stop_reason = f"spend_refused: {exc}"
            report["walk"].append({**s, "status": "spend_refused", "detail": str(exc)})
            print(f"  [{i + 1}/{len(plan)}] STOP — {exc}")
            break
        except model_stub.ModelSubstitutionError as exc:
            stop_reason = f"model_substitution: {exc}"
            report["walk"].append({**s, "status": "model_substitution", "detail": str(exc)})
            print(f"  [{i + 1}/{len(plan)}] STOP — {exc}")
            break
        except (model_stub.ModelInvocationError, model_stub.ModelRateLimitError) as exc:
            report["walk"].append({**s, "status": "invocation_error", "detail": str(exc)})
            print(f"  [{i + 1}/{len(plan)}] error — {exc}")
            continue

    report["records"] = [r.to_dict() for r in records]
    report["g1"] = g1_block(records)
    report["expectations_v2"] = expectations_v2(records, consumer_model=model_id)
    report["stop_reason"] = stop_reason
    report["calls_made"] = made
    report["calls_reused"] = sum(1 for w in report["walk"] if w["status"] == "reused_evidence")
    report["spend"] = ledger.status(run_id)
    report["finished_at"] = _now()
    out = RESULTS / f"g1_v2_run_{run_id}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=1, ensure_ascii=False, default=str) + "\n", encoding="utf-8")
    print(f"\nstop: {stop_reason}; calls made {made}/{n_calls} (reused {report['calls_reused']}); family records {len(records)}")
    a_ = report["g1"]["observed"]["all"]
    print(f"  all: n={a_['n']} scored={a_['n_scored']} unparseable={a_['n_unparseable']} L3+={a_['preserved']} rate={a_['preservation_rate']}")
    for sf, cells in report["g1"]["observed"]["by_surface_and_compression"].items():
        for comp, cell in cells.items():
            print(f"  {sf:14s} {comp:7s} n={cell['n']:3d} scored={cell['n_scored']:3d} unp={cell['n_unparseable']} L3+={cell['preserved']:3d} rate={cell['preservation_rate']}")
    print(f"results: {out.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
